### ISSUE TITLE
Three dots are appearing and disappearing on editor because of GitLens.

### ISSUE THREAD

**Issue by ankitjain-1** [gitkraken/vscode-gitlens#1312]
- GitLens Version: 11.1.3
- Git Version: 2.29.2

- VSCode Version: 1.52.1
- OS Version: manjaro linux 20.2

Steps to Reproduce:

1. Start writing something on editor, three dots appears and disappears after some seconds.
This looks too annoying because whole code shifts down and up after again and again.
I tried installing some previous versions of GitLens but this is still issue there.

For reference go to this link ( someone reported same issue on vscode repository ): 
[https://github.com/microsoft/vscode/issues/111472#issue-752993771]()

**Comment by thisisrandy** [comment]
It appears that gitlens uses an ellipsis as a placeholder for "Recent change" information. If that feature is enabled, text along the lines of "AUTHOR, TIME ago | X authors (AUTHOR)" appears at the top of files and code blocks. When the user begins editing the file, that text appears to be replaced with "...". A few seconds after the user has stopped editing, gitlens seems to refresh and display the (potentially updated) recent change text.

The problem arises when a file is untracked. Since there is no recent change information to speak of, gitlens does not display it. However, a file-level ellipsis is displayed when editing, which causes a new line to appear and the code on-screen to jerk down and then back up again once editing has ceased. A stack overflow user [suggested](https://stackoverflow.com/a/71322230/12162258) that disabling the recent changes feature will fix this, but it does not.

This is hopefully a simple fix: before taking any action to modify display, gitlens could simply check if the file in the focused editor pane is being tracked and do nothing if not. Might someone who knows the code dig in and make the fix?

**Comment by eamodio** [comment]
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1742

**Comment by thisisrandy** [comment]
Confirmed fixed in v12.0.1.

**Comment by moop-moop** [comment]
Seem to be back in v12.0.5

**Comment by eamodio** [comment]
@moop-moop Can you capture a video of what you are seeing?

**Comment by xiangnanscu** [comment]
@eamodio see mine https://github.com/microsoft/vscode/issues/146379

**Comment by xiangnanscu** [comment]
I confirm the version is v12.0.5

**Comment by eamodio** [comment]
@xiangnanscu 

The existance of `...` is by design -- because once you start editing the file the blame CodeLens become "invalid", and if I remove them the file will jump around, so I replace them with `...` until the file is saved or 5s has passed since the last edit. If you want to avoid the `...` you can decrease the default (5s) timeout using the `"gitlens.advanced.blame.delayAfterEdit"` setting. This will avoid the `...` and update the CodeLens quickly, but it will cause more processing to more regularly re-compute the blame.

But the `...` shouldn't show up, and then completely disappear causing the file to jump, which is what this bug was about.

**Comment by xiangnanscu** [comment]
@eamodio OK. thanks for the tip.
