### ISSUE TITLE
Forced regular expression search in changes

### ISSUE THREAD

**Issue by tormozit** [gitkraken/vscode-gitlens#1572]
- GitLens Version: v11.5.1
- OS Version: Windows 10
- VS Code Version: 1.58.0 (user setup)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0

Steps to Reproduce:

1. In Visual Studio Code connect to cloned repository from https://github.com/tormozit/RDT1C
2. Open GitLens/Search&Compare/Search in changes
3. Turn Off "Regular expression mode"
4. Type "div|p|b"
5. Run command
![изображение](https://user-images.githubusercontent.com/11896251/125033501-0f395b00-e098-11eb-9a32-7f3692c1a1b0.png)

I get billion of results instead of just several. It looks like "Regular expression mode" is always ON even if switch is OFF.

**Comment by eamodio** [comment]
This should largely be resolved, but unfortunately turning the regex on and off will have more of an effect and just not using a regex to match should. This is because Git doesn't seem to support searching in diffs for literal strings (only regex via the `-G` flag to `git log`), but it can search for occurrence differences of literal strings (via the `-S` flag to `git log`).

Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by tormozit** [comment]
Disabled stable GitLens version. Installed GitLens Insiders version. Problem reproduced
![изображение](https://user-images.githubusercontent.com/11896251/147050226-008cae9d-9ae2-4b89-8ecc-6552511fcfc7.png)

**Comment by eamodio** [comment]
@tormozit Sorry but the latest insiders isn't out just yet (should be published in the next 10m). It will be version `2021.12.22*`
