### ISSUE TITLE
Loses commit and file selection in history

### ISSUE THREAD

**Issue by Wolfenberg** [gitkraken/vscode-gitlens#1596]
- GitLens Version: 11.6.0
- Git Version: git version 2.30.1 (Apple Git-130)

- VSCode Version: 1.58.2
c3f126316369cd610563c75b1b1725e0679adfb3
x64
- OS Version: MacOS Big Sur 11.4 (20F71)

Steps to Reproduce:

1. Open some commit in history and select a file.
2. Use VSCode for a while.

At some point Gitlens collapses the history and selected commit and file is lost (have to search for it again). It's a problem if doing post commit code review.

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!
