### ISSUE TITLE
Gitlens cause vscode runs very slow

### ISSUE THREAD

**Issue by PabloLION** [gitkraken/vscode-gitlens#1642]
## ENV
- GitLens Version: v11.6.0
- Git Version: git version 2.27.0.windows.1
- VSCode Version: 1.60.1
- OS Version: Windows 1902

## Steps to Reproduce:

1. open a large project
2. type some "scope"(trigger of snippet)
3. see how long the intelisense will popup

## Realated issue 
#509

## Obsevation
- My current work around
after disabling `gitlens.advanced.blame.sizeThresholdAfterEdit`(set to 0) and with `gitlens.advanced.blame.delayAfterEdit` set to 15000. The issue is relieved a lot.

**Comment by Pablion** [comment]
It's for SEO since every time I google this problem I see #509.

**Comment by eamodio** [comment]
@PabloLION is this related to the size of the file you are editing or the size of the repository? I'm a bit confused how GitLens would affect the speed of intelisense (other than just pure contention for resources)

**Comment by PabloLION** [comment]
Thanks for the reply @eamodio. It's only caused by the size of file anyway (however, when the file becomes larger, intelisense shows up even slower), because even if I create a new file it's still slow. It might be for the size of repo. And it does affect the speed of intelisense showing up. I think this might be caused by some vscode internal engine, because since I moved to apple (2month ago), this problem was gone. Also, in the "Extension view" the reported usage time is not as much as I waited (reported total time 200~300ms, everytime I had to wait for at least 50ms for intellisense to show up, after I set the delay to 0ms) 
So I had to stop the GitLens to correctly use my snippets and intelisense.

If you want to resolve this, I still have access to my windows, maybe we can work this out.

**Comment by eamodio** [comment]
I would definitely love to improve the performance for sure. And you only see the performance issue when GitLens is enabled? If so can you try profiling GitLens?

You can profile by running _Developer: Show Running Extensions_ from the Command Palette, and then right-click on GitLens and choose _Start Extension Host Profile_

![image](https://user-images.githubusercontent.com/641685/147064059-f92177ea-43ea-4a2d-8632-45a92faed31a.png)

It will likely make you restart VS Code to enable it -- and then you will need to repeat the same steps. But then once the profile is running, reproduce the problem (a couple of times maybe), and the stop the profile and save it.

Then I could take a look to see what the bottleneck might be.

**Comment by PabloLION** [comment]
> I would definitely love to improve the performance for sure. And you only see the performance issue when GitLens is enabled? If so can you try profiling GitLens?

Yes and yes.

I'll try it when I go play games on windows later.

**Comment by PabloLION** [comment]
Here are these files. 
The "activation time" dosn't affect the delay tho, nor does the extension manage tab panel. I hope this will be helpful. Thank you again.

Please ask more if needed.

[with-gitlense-CPU-20211225T174137.078Z.cpuprofile.txt](https://github.com/gitkraken/vscode-gitlens/files/7776094/with-gitlense-CPU-20211225T174137.078Z.cpuprofile.txt)
[Without-GitLens-CPU-20211225T174016.136Z.cpuprofile.txt](https://github.com/gitkraken/vscode-gitlens/files/7776095/Without-GitLens-CPU-20211225T174016.136Z.cpuprofile.txt)

**Comment by eamodio** [comment]
@PabloLION Thank you for the traces. Digging into them I can't really identify what GitLens is doing to cause issues, but a couple of things stand out in the trace:

There are 3 calls to WASM functions, which are each taking about 1.4s -- I don't see those same WASM calls without GitLens, though I'm not sure I can rely on the `wasm-function[*]` matching on both sides. Those WASM calls aren't coming from GitLens, but from the _Bracket Pair Colorizer_ extension (which by the way should no longer be needed since bracket colorization is built into VS Code because of the performance issues that couldn't be fixed in that extension -- you can read the details on this on the [VS Code Blog](https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization)) 

Additionally, I also see the built-in Git extension doing a lot more work (though nothing that should cause delays like the above) in the GitLens trace. I'm not sure why that would be.

So I think there is some interaction between GitLens and the _Bracket Pair Colorizer_ extension which causes some a performance issue (it might account for all of the visible issue). I'm guessing it is because both are adding decorations into the editor, but I'm not sure how they actually are interacting badly.

Could you please try again after disabling/uninstalling the _Bracket Pair Colorizer_ extension to see if you still see an issue?

If that doesn't completely resolve the issue, can you try to see if the issue is still reproducible in the GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). 

Please be sure to disable or uninstall the stable version of GitLens first.

Thanks!

**Comment by PabloLION** [comment]
Thank you for being very serious to this problem. I think I uninstalled the the pair bracket color extension because it's integrated into VSCode. Later I'll check that and confirm what's happening. Thank you.

**Comment by PabloLION** [comment]
Hi team. I just tested again with bracket pair colorizer 2 turned off. The delay with and without GitLens is the same(both need to wait for 1.5s). I this the delay is not caused by GitLens, and since I moved to Mac and there's nothing to report, I'm closing this issue. Thanks for your attention.

**Comment by eamodio** [comment]
Thank you!
