### ISSUE TITLE
element with id xxx is already registered

### ISSUE THREAD

**Issue by ForgottenR** [gitkraken/vscode-gitlens#1680]
- GitLens Version:v11.6.1
- Git Version: git version 2.33.0.windows.2
- VSCode Version:
1.61.0
ee8c7def80afc00dd6e593ef12f37756d8f504ea
x64
- OS Version:
Edition	Windows 11 Pro
Version	21H2
Installed on	‎10/‎6/‎2021
OS build	22000.194
Experience	Windows Feature Experience Pack 1000.22000.194.0

Steps to Reproduce:

1. add two remote repositories (in this case https://github.com/discretize/discretize-gear-optimizer/ and https://github.com/lcdlyxrqy/discretize-gear-optimizer)
2. the error information will pop when I add the second repository or every time I refresh all remote repositories. In my case the specific informations is "Element with id gitlens:repository(c:/Users/xxdsz/Documents/Web/discretize-gear-optimizer):branch(origin_mine/new-data-modifier-amounts) is already registered"

**Comment by Stephenmccaul** [comment]
This happens to me nearly constantly when browsing in the branches menu when looking at submodules. Concurrent with this message the change history in the branch disappears and will not come back entirely breaking the branches view.

**Comment by EWinner1** [comment]
I have the same question, but it can be fixed by disable the extension and re-enable it to fix it. But actually, I don't know why it will work like this.

**Comment by tomika** [comment]
Similar problem here, but nor VSCode restart nor plugin disable/resinstall helps.
![image](https://github.com/gitkraken/vscode-gitlens/assets/116955/898fab77-9cf5-4417-8077-5e557aa0bc46)
Gitlens v13.6.0 (also tried actual pre release version)
git version 2.40.1.windows.1

The problem persistent, occures every time I try to use search function in Search and Compare tab.
Seems search successfull since count of found elements displayed, but the tree is empty:
![image](https://github.com/gitkraken/vscode-gitlens/assets/116955/259166ea-86f2-4d3b-b1d5-a49a6dba5144)
and the following error displayed:
"Element with id gitlens:repository(c:/repo/path):stash(...) is already registered"
The stash uuid always changing

**Comment by jkelroy** [comment]
Hello @tomika and others, this looks similar to #2144. [As I mentioned there](https://github.com/gitkraken/vscode-gitlens/issues/2144#issuecomment-1609645710), I am no longer seeing this error in GitLens 14+. Can you please try updating and let me know if this persists?

**Comment by tonypags** [comment]
I haven't had this issue in a while. I noticed at some point the git lens started graying out commands when I run a command so that I can't run commands in parallel--which makes sense. I haven't seen this error since then, at least.
