### ISSUE TITLE
GitLens stopps PHP xDebug from working

### ISSUE THREAD

**Issue by 7118path** [gitkraken/vscode-gitlens#1825]
Hi,

I am using xdebug.php-debug to debug a PHP application running in a container. Suddenly I was not able to use the debugger anymore. Using the normal 'Run -> Start Debugging' just resulted in ....nothing. I found nothing in any of the logs of vscode.

After some search I found the debugger is working again after having GitLens disabled.

It would be great if you could look into this.

TIA

**Comment by picarro-mbuckner** [comment]
This issue is also preventing the Python debugger from working as well. Disabling GitLens allows the debugger to work properly. Re-enabling re-breaks the functionality.

**Comment by eamodio** [comment]
Can you provide more details (with exact steps) to what you are seeing? A video might help too. I can't see how GitLens could be negatively affecting the debugger.

**Comment by picarro-mbuckner** [comment]
My original issue was extremely straightforward to reproduce. Open python file, start debugging with a "Python: Current File" launch configuration, nothing would happen. There would be no other logs in the developer tools console.

I think I figured out my issue though. I'm not sure how this happened but I ended up with a gitLens entry in my .workspace that appears to be the culprit, though I'm not sure exactly how. Maybe because the reference didn't exist? I'm not sure how it got there, but removing it fixed my debug issues. Again there was no log in the developer tools console.

The offending entry in my "folders" section of my workspace, and my python launch configuration for reference (the python path is correct).

![image](https://user-images.githubusercontent.com/40368761/160545090-193b909a-6c49-4f3f-96de-600e086b586c.png)
