### ISSUE TITLE
gitkraken.gitkraken-authentication should be optional

### ISSUE THREAD

**Issue by superole** [gitkraken/vscode-gitlens#1853]
- GitLens Version: 12.0.0
- Git Version: N/A

- VSCode Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. Update GitLens from v11.7.0 to v12.0.0

Expected behaviour:

1. GitLens is updated, possibly with new features and less bugs (not that I have noticed any previously)
2. Nothing else

Actual behaviour:

1. GitLens is updated
2. The optional-to-use connected extension "gitkraken.gitkraken-authentication" is forcibly installed and marked as dependency so it cannot be uninstalled without uninstalling GitLens too

Workaround:

Install v11.7.0 again

**Comment by AnWeber** [comment]
You would have to remove the dependency from the [package.json](https://github.com/gitkraken/vscode-gitlens/blob/v12.0.0/package.json#L51) and make the use of the extension optional in the code. But I did not find any usage of this dependency.
While searching for the usage I noticed the currently not used method [`installExtension`](https://github.com/gitkraken/vscode-gitlens/blob/v12.0.0/src/partners.ts#L8).

**Comment by SE2Dev** [comment]
Also somewhat related, GitLens no longer activates correctly in dev containers as a result of `gitkraken.gitkraken-authentication`.
![image](https://user-images.githubusercontent.com/5873790/156206834-877d302e-0e0b-433e-84d8-1bf102f2643c.png)

**Comment by eamodio** [comment]
This has been resolved in the latest GitLens insiders edition (will be released to GitLens stable very soon).

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by queensferryme** [comment]
While I believe by introducing the GitKraken extension @eamodio did mean no harm, and I appreciate his efforts to commercialize such a wonderful open-source software, it is still kinda creepy to have an extension installed on your machine without being noticed or asked for permission.

Therefore, I have opened an [issue](https://github.com/microsoft/vscode/issues/144714) in the vscode repo, and I hope vscode will handle such cases (new extension dependency) better in the future. Please consider upvoting ♥️

**Comment by eamodio** [comment]
It was certainly not intended to do anything but separate authentication from the core of GitLens (following the auth extension pattern of the built-in GitHub and MS auth providers in VS Code itself). And the GK Auth extension literally does nothing else.

My main motivation for creating a separate extension was:
  a) that if felt odd that GitLens provided GitKraken authentication to VS Code -- because the VS Code authentication system is "global"
  b) in the future it might be valuable to allow other extensions to use GitKraken authentication if they desired (this is pretty useless right now, but we have plans for cloud services that could be useful later)
  c) avoid making GitLens a bit bigger because of extra code

But clearly this caused a lot of confusion (and real anger which I'm sorry for but honestly really surprised by), so I removed it as quickly as possible to ensure the community was heard and respected.

**Comment by superole** [comment]
I totally agree with all your points, @eamodio, and I think it is excellent that you decided to create a separate extension. The only problem for me was the dependence, and you solved that super quick!

**Comment by AnWeber** [comment]
@eamodio I can very well understand your reasons for the extension and agree with them. From my point of view however, this was unfortunate, because a few points have coincided:

- The takeover by gitkraken
- The change was not visible in the main branch, but only hidden (v12 branch).
- The extensionDependency was not necessary as the extension is not used directly, but only via VSCode Api interfaces.

The points left me with the feeling that it was not your decision to reference the extension but a company decision to promote a new feature/ customer acquisition. But this has been resolved in the meantime

**Comment by eamodio** [comment]
@AnWeber Not sure what you mean by
> The change was not visible in the main branch, but only hidden (v12 branch).

All GitLens versions are built via the GitHub actions in the repository and off of the `main` branch, so all changes are visible in the repository.

As for the dependency, it was required -- that's why I set it up that way. For GitLens to use the authentication, the extension would have to be installed and registered with VS Code as an authentication provider. And just as GitLens talks to the GitHub authentication provider to know if you've allowed GitLens access to GitHub, it needs to do the same thing for GitLens+ access. If you've never signed in, then the auth provider just returns saying there is no saved session, and GitLens knows there isn't a GitLens+ account that can be signed into, but if there was a saved session, then GitLens can connect the account, etc.

**Comment by AnWeber** [comment]
@eamodio At the time I searched the code for the reference to the extension, it was only visible in tag v12. For this reason I linked the package.json of the tag in my first comment. The main branch was not up to date, which irritated me and thus the github search did not work (searches only main branch). Or that's how I remember it.

I think you do an excellent job with this extension. Probably that is even an understatement.

**Comment by eamodio** [comment]
@AnWeber Thank you, I really appreciate that! I think what might have happened, is you looked on `main` after I already removed the dependency. Here's the commit that removed it: https://github.com/gitkraken/vscode-gitlens/commit/59ee1d2b5042f38a7fd28370590b46d9984e3938 which was on `Mar 1 at 12:35 EST`, and your post above was on `Mar 1 at 5:05 EST`.
