### ISSUE TITLE
Blame line popout is displaying old Gravatar

### ISSUE THREAD

**Issue by amouxaden** [gitkraken/vscode-gitlens#1898]
- GitLens Version: v12.0.3
- Git Version: 2.34.1.windows.1
- VSCode Version: 1.65.2 x64
- OS Version: Windows 10.0.19044.1526 LTSC

Using GitLens I noticed that the pop out Gravatar displayed is stale and not updating as fast as it should.

![image](https://user-images.githubusercontent.com/20881869/157776550-56921f13-4f64-42dc-8339-3dc15ed76323.png)

![image](https://user-images.githubusercontent.com/20881869/157776602-d813bca5-76b6-465a-bd38-5e5a2292bdb4.png)

Steps to Reproduce:

1. Update Gravatar on https://en.gravatar.com/
2. Check pop out by hovering over blame line.
3. Note that Gravatar is stale

I noticed that to alleviate this issue you can simply omit the '.jpg' in the request as GitLens sends a request (with my email hash) for 
https://www.gravatar.com/avatar/e59f9ec19fc467009d1e4cea53f959cb.jpg?s=64&d=robohash
and not
https://www.gravatar.com/avatar/e59f9ec19fc467009d1e4cea53f959cb?s=64&d=robohash
for a faster change.

**Comment by eamodio** [comment]
@amouxaden are you actually seeing a difference from gravatar itself, meaning if you update your image and you hit:
https://www.gravatar.com/avatar/e59f9ec19fc467009d1e4cea53f959cb.jpg?s=64&d=robohash
vs
https://www.gravatar.com/avatar/e59f9ec19fc467009d1e4cea53f959cb?s=64&d=robohash

You see a different version?

Or is this only in GitLens? I ask because GitLens caches avatars to avoid refreshing them often. I forget off hand for how long I cache them for before expiring them (but it's pretty long). You can always run the `GitLens: Reset Avatar Cache` from the Command Palette to make GitLens drop the cache and re-request the avatars.

**Comment by amouxaden** [comment]
@eamodio Yes precisely. I'm seeing a difference from the request that includes the `.jpg` vs the one that doesn't. It looks like this is a caching issue on Gravatars end but could possibly be resolved in the extension with omitting the file extension from the request. 

Regarding the `GitLens: Reset Avatar Cache`, running from the command palette has no effect on my gravatar as I believe it reloads the old one again from gravatar with the file extension included.

After making a test build of GitLens with the file extension excluded, it was successfully able to load the most up to date version. I published this change with #1899

**Comment by eamodio** [comment]
OK, awesome -- thank you so much for the investigation and PR! I will get that PR merged in for the next release. ❤️
