### ISSUE TITLE
Can't Get Past Welcome Screen

### ISSUE THREAD

**Issue by jonathan-wondereur** [gitkraken/vscode-gitlens#1919]
- GitLens Version: 12
- Git Version: 2.35.1

- VSCode Version: 1.65.2
- OS Version: Ubuntu 20.04.3 LTS

Steps to Reproduce:

1. Open a new environment on GitPod.io
2. Can not sign in or close welcome dialogue to get to GitLense interface in the sidebar.

**Comment by eamodio** [comment]
@jonathan-wondereur Can you show a screenshot of what you mean? You should not need to sign in or anything. Unless you want to, to access the two new GitLens+ features (Visual File History & Worktrees)

**Comment by pagdot** [comment]
not sure if this is related. But wasn't able to skip the free trial without disabling GitLens+ in the settings

**Comment by jonathan-wondereur** [comment]
Sure @eamodio this is what I see when I go to the GitLense panel in VS Code on GitPod. I can not get past this screen.

![image](https://user-images.githubusercontent.com/38539725/159472178-a484aabe-b410-40ca-852c-88b585a15473.png)

**Comment by murphyke** [comment]
@jonathan-wondereur: I'm sure you managed to get past this, but in case it helps others, just to elaborate on what @pagdot said (thanks, pagdot), you can get past the Introducing GitLens+ content by turning off the `gitlens.plusFeatures.enabled` setting. You can do that by running the `Preferences: Open Settings (UI)` command and searching for gitlens+.

**Comment by eamodio** [comment]
You can also run the command from the command palette to hide them.  But to be clear, there is *nothing* to get past -- this view isn't a gate for anything "under" it. This view currently is informational. GitLens views and functionality live in other places in the VS Code UI, mainly on the Source Control activity bar.

**Comment by eamodio** [comment]
Can those who are confused, elaborate on what apsect is confusing? As there is no need to "get past" anything. The GitLens Home view is a view that helps you get started with GitLens -- what's new & support resource links, getting started steps and helpful video, info about where most GitLens views live (and have always lived), info about integrations (and eventually will help guide you to set them up), and then GitLens+ features.

It is a sidebar view like any other view, which you can switch between as any other view.

**Comment by ZebraFlesh** [comment]
Sure: I was forced to reboot my computer for the first time in a while. VSCode is set to automatically update extensions. So when I had finished rebooting and logging in, I went to VSCode and started to try to work. But I was presented with the GitLens sidebar: it was focused and clearly displaying that it had updated to v13. Great, extensions do this to tell me what new features they have, cool. I start looking for a "dismiss" button. Can't find one. Start scrolling through and see something about having to pay to support private repos. Start freaking out. Start going through with a finer tooth comb, reading things, trying to find how to dismiss it and get back the free functionality that I had enjoyed. Eventually wound up here and figured it out it's no big deal, just ignore it.

There were a few issues with the UX:
1. Autofocus when starting VSCode. I understand y'all need to advertise, but users need an escape key.
2. No escape hatch. Makes it look like I'm being forced to move to a paid version, or at a minimum sign in (which I don't want to do).
3. Loooooong text. Give me some CTAs that link to the long text and make the user path through that screen more obvious.

By comparison, one of my AWS extensions also updated during this process. I received a minimally invasive toast notification that informed me of the update and had an X that allowed me to dismiss the notification. I was informed, and the software got out of my way. No sidebars were focused, etc.

**Comment by eamodio** [comment]
We only show the sidebar view on first install and major version releases. The intent is to help users get started with all the functionality GitLens provides, see what's new, etc. 

I will see if it is possible for us to trap ESC and have it close the side bar. But curiously why would you be looking for a "dismiss" button or escape hatch? Was it not clear that it was a side bar view like explorer, search, scm?

I agree there is a lot on that view, but it is broken up into stepped sections to help you get started. There is nothing you _have_ to do here, its just meant to be a helpful tool for onboarding, discovery, and exposure to GitLens+ features, if you want them.

Was it the header that helped cause confusion?

![image](https://user-images.githubusercontent.com/641685/197067174-86cfb223-c8ec-496a-8a3a-942c7b257940.png)

Is that what made you "freak out" and make you feel like you need to do something here?


For reference, here's the view we are talking about:

![image](https://user-images.githubusercontent.com/641685/197064706-de934a7a-48f4-432f-956a-f3b452b79e5f.png)

And here it is with all the sections collapsed, and "what's new features" dismissed

![image](https://user-images.githubusercontent.com/641685/197064841-11bd5fb9-7de5-4b3b-95fa-36fb62ddd376.png)

**Comment by murphyke** [comment]
> It is a sidebar view like any other view, which you can switch between as any other view.

I think the issue may be that people aren't used to a sidebar view that isn't "functional". Since the majority of sidebar views allow you to _do_ something, that is why some people are thinking, "how can I dismiss this documentation and get to the good stuff?"

For introductory verbiage, people are used to going to the relevant extension via the Extensions sidebar. The freakout factor comes from this deviation from common experience combined with the fact that the only functional part of the sidebar is the "Start Pro Trial" button and the "Sign In" button. The latter button makes it seem like even to get free GitLens features, you have to sign in, which some people may not like.

I would recommend adding a very brief paragraph at the top of your welcome section explaining the situation clearly, e.g. "This panel is for ______. GitLens Free features are integrated in the appropriate places in VS Code; see below for details. You do/do not need to have an account to use the GitLens Free features. However, we hope you will try GitLens Pro, which is awesome because ____."

**Comment by ZebraFlesh** [comment]
I was typing a big long thing, but I think @murphyke put it more succinctly.

> I will see if it is possible for us to trap ESC and have it close the side bar. But curiously why would you be looking for a "dismiss" button or escape hatch? Was it not clear that it was a side bar view like explorer, search, scm?

By "escape", I'm talking in a UX sense -- not a literal keyboard sense. A similar situation is being presented with a dialog that wants you to sign in, but there's no cancel button or a way to close the dialog. That's _exactly_ what this felt like: I was being forced to sign in/up in order to keep using the product (extension). Given the 3 CTAs here, we're missing some user path out of this sidebar that isn't one of those 3 CTAs. The wording suggestion above is a good one. Another option is something like a "Okay, I understand" button which hides the documentation, has a button to show the docs again, and perhaps a nice marketing "Thanks for using GitLens!" sort of message.

**Comment by pagdot** [comment]
I could imagine a web view in the main view could be better suitable. Similar to release notes by vs code or a tutorial one used by some other extensions

**Comment by ZebraFlesh** [comment]
What additional info is needed at this time?

**Comment by eamodio** [comment]
Nothing -- it was an overzealous bot. We are working on some changes and will post some designs soon.

**Comment by eamodio** [comment]
Since GitLens we've overhauled the Home and welcome experience and this should no longer be an issue.
