### ISSUE TITLE
gitlens not showing or working

### ISSUE THREAD

**Issue by the-cat-d** [gitkraken/vscode-gitlens#1986]
im currently on gitlens 12.0 and it seems like none of features are working, not even the ui nor the commands (most of them)
ive had this problem for almost a week now and i still cant fix the issue

got any solutions?

**Comment by TanninOne** [comment]
Not a great solution but: vscode lets you downgrade to 11.7.0 which works nicely afaict (click the cog wheel on the extension, then "Install Another Version")

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in the GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). 

Please be sure to disable or uninstall the stable version of GitLens first.

If that doesn't help, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!
