### ISSUE TITLE
Have an always-on option for the blame heatmap

### ISSUE THREAD

**Issue by Nicholas-Autio-Mitchell** [gitkraken/vscode-gitlens#1988]
I can toggle the file heatmap and it displays in the gutter just fine.
However as soon as I edit the file, the heatmap disappears (also asked [back in 2020 here](https://github.com/gitkraken/vscode-gitlens/issues/426), but never addressed).  After disappearing, I need to once again toggle it on.

Could we have an option to just have the gutter heatmap always on? Or link it to `Gitlens > Advanced > Blame: Delay After Edit`?

**Comment by eamodio** [comment]
I like this suggestion -- I was hoping it was something I could easily add, but unfortunately it will take a bit more work than I had hoped, so I've put it on the backlog.

**Comment by eamodio** [comment]
In the current pre-release of GitLens there is a new experiemental setting that can be enabled to provide this behavior. Set `"gitlens.experimental.allowAnnotationsWhenDirty": true` to enable this new behavior, and now file annotations (blame, heatmap, changes) will be more persistent rather than going away on an edit. That setting also works in tandem with the existing `gitlens.advanced.blame.delayAfterEdit` which defaults to 5s -- which means after an edit it will take 5s before the annotations are recomputed. Lowering that will improve responsiness but increase the performance overhead.

Let me know what you think of the new behavior. Thanks!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by tristan957** [comment]
In #426, you said this would be performance intensive. Is that still the case?

**Comment by eamodio** [comment]
Depends on a few factors:

- how fast your machine is or contention
- how large the file you are editing is
- how short the after edit blame delay is set to (5s by default which is VERY conservative)

I've been playing with it on my fast machine and I can set the after edit delay to 1ms and I don't notice any impact to typing or otherwise.

**Comment by tristan957** [comment]
Thanks for your hard work on this extension as always!

**Comment by Nicholas-Autio-Mitchell** [comment]
Thank you for the big improvement, @eamodio!  It works exactly as you described for me :)

Is there a way to enforce the git blame heatmaps to be always on? I toggle them on, they work for the current file and new files I open. However if I close all git-tracked files (e.g. whilst working on others that are not yet git-tracked), then open any git-tracked file, the heatmaps are not turned on.

Thanks in advance!

**Comment by eamodio** [comment]
@Nicholas-Autio-Mitchell thanks! Can you open a new issue with a bit more details on the exact scenario that doesn't work? And do you have the heatmap set to be toggled for the whole window?
