### ISSUE TITLE
Failed to login with GitHub account on safari

### ISSUE THREAD

**Issue by changxiaoqiang** [gitkraken/vscode-gitlens#1993]
- GitLens Version:
- Git Version: Run `git --version`

- VSCode Version: Run `code --version`
- OS Version:

Steps to Reproduce:

1.

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the _GitLens_  channels.

Thank you!
