### ISSUE TITLE
 `git.commit` is not a valid menu identifier

### ISSUE THREAD

**Issue by usta** [gitkraken/vscode-gitlens#2055]
I am getting this error/warning in logs 

[2022-06-25 18:47:40.559] [renderer1] [info] [eamodio.gitlens-insiders]: `git.commit` is not a valid menu identifier

- GitLens Version: It is same in both stable and insider channels of gitlens 
- Git Version: git version 2.36.1.windows.1
- VSCode Version: 1.69.0-insider
- OS Version: Windows 10 Professional 21H2 Build 19044.1766

**Comment by d13** [comment]
Can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the _GitLens_ channel.

Thank you!

**Comment by eamodio** [comment]
Yeah, unfortunately there is no way for GitLens to silence this warning (as vscode contributions are all statically defined) -- This issue because GitLens wants to add a menu to the built-in Git "commit" menu (if its there), but vscode is trying to "helpfully" warn the extension developer that the menu its trying to add to doesn't exist -- which made sense when extensions could not dynamically add submenu contributions, but now that they can, this warning is annoying for those cases.

I was able to get VS Code to remove the notification it used to show for this case, but I wasn't successful on getting the warning removed: https://github.com/microsoft/vscode/issues/140463

**Comment by usta** [comment]
@eamodio if we couldnt check it [if Git-base disabled or not] at least we can add this on in documentation. I mean could you at least add a section called FAQ in Readme.md and mention this one in there so if somebody hit this like me can see and fix it easily by enabling git-base extension. Thank you

**Comment by eamodio** [comment]
There is no way to check -- its a static registration in the `package.json`. We can think about adding a FAQ area or support note about this -- though it isn't an issue if you see this (and you only see it in the console/vscode renderer logs) its merely a warning.
