### ISSUE TITLE
Your 'github' credentials are either invalid or expired

### ISSUE THREAD

**Issue by tekumara** [gitkraken/vscode-gitlens#2067]
- GitLens Version: v12.1.1
- Git Version: Run `git --version`

- VSCode Version: 1.68.1
- OS Version: macos

Steps to Reproduce:

1. Connect to Github Enterprise, eg: settings 
    ```
    "gitlens.remotes": [{ "domain": "github.acme.com", "type": "GitHub" }]
    ```
2. Open git blame, connect to github and authorise

Gitlens is stuck in a loop where it will now keep popping up the 
```
Your 'github' credentials are either invalid or expired. Would you like to try reauthenticating?
```
box, and the modal window:
```
Are you sure you want to disable
the rich integration with GitHub
(github.acme.com)?
```

Reauthenticating doesn't work, nor does disabling the integration. In either case, both dialogs will reappear.

**Comment by jnpwly** [comment]
I _think_ I might have stopped this behaviour, by disallowing the GitLens extension from accessing my (regular, non-enterprise) Github account:

![image](https://user-images.githubusercontent.com/10701621/180331629-1a6df6c3-9af1-4e44-b828-1e14746ad476.png)

![image](https://user-images.githubusercontent.com/10701621/180331752-de4cf76a-1f8e-42b6-912a-ef96658cee19.png)

![image](https://user-images.githubusercontent.com/10701621/180331921-cb05a2bd-189b-43d1-b640-01b25fdd9766.png)

After I removed the permission for GitLens to use my (regular, non-enterprise) Github account, I was no longer prompted to authenticate. I guess there's a bit of confusion/overlap between the (regular, non-enterprise) Github account as configured within VS Code itself, and the Github Enterprise account configuration specifically for GitLens. But that's just a guess.

**Comment by rockboynton** [comment]
> I _think_ I might have stopped this behaviour, by disallowing the GitLens extension from accessing my (regular, non-
> After I removed the permission for GitLens to use my (regular, non-enterprise) Github account, I was no longer prompted to authenticate. 

After doing that, and hovering on a line I get this 
![image](https://user-images.githubusercontent.com/32227280/180336019-a3638479-1c28-456d-932f-b5496151835e.png)
then when I click "Connect to GitHub", I'm back to square one 😢

**Comment by bryankenote** [comment]
Rolling back to 12.1.0 resolved this for me.

**Comment by eamodio** [comment]
Sorry for all the trouble and confusion on this one. To get GitLens (or more accurately VS Code) to use GitHub Enterprise, You need to set `github-enterprise.uri` in your settings to the URL of your enterprise instance. But the stable version of GitLens (currently 12.1.2) doesn't yet support GitHub Enterprise -- you'll need to try the Insiders version of GitLens.

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

I am looking into ways to improve this auth flow, and avoid some of the confusion here -- since ideally you shouldn't get  prompted to auth for a GitHub Enterprise remote, unless you have `github-enterprise.uri` or better we should guide you to set it.

**Comment by eamodio** [comment]
The latest insiders build changes the authentication for GHE to be completely controlled by GitLens to avoid the need for the `github-enterprise.uri` setting and to allow multiple GHE instances to be connected to at once. This should completely resolve this now.
