### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by te190087** [gitkraken/vscode-gitlens#2074]
- Issue Type: `Bug`
- Extension Name: `gitlens`
- Extension Version: `12.1.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!
