### ISSUE TITLE
Color style for icon not applicable

### ISSUE THREAD

**Issue by bmarvinb** [gitkraken/vscode-gitlens#2087]
I want to customize the default icon color, so I changed it in the settings
```
      "list.activeSelectionIconForeground": "#2e3440"
```
But it didn't change an icon in the commit view
![image](https://user-images.githubusercontent.com/23120972/178949091-366f27f8-0faa-4141-9586-8031832f3c3c.png)
It is still white, how to change this icon too?

**Comment by eamodio** [comment]
I believe the difference in the icons there is because some of the icons are built-in to VS Code (e.g. codicons) that GitLens can use, and the white one is a custom SVG that GitLens provides. Other than GitLens converting its custom SVGs into a custom codicon set (which I am planning to do in the near future, since it is now possible in VS Code) I don't think there is any way for me to fix this.

**Comment by eamodio** [comment]
Depends on https://github.com/gitkraken/vscode-gitlens/issues/958

**Comment by d13** [comment]
Resolved with https://github.com/gitkraken/vscode-gitlens/commit/8fa90c2c6d95431c96afef59bc9092fec154480e

**Comment by d13** [comment]
@bmarvinb our latest release adds custom codicons so you should see you custom colors!
