### ISSUE TITLE
GitLens requires a newer version of Git (>= 2.7.2) than is currently installed (GNU bash, version 4.4.23(1)-release (x86_64-pc-msys) Copyright (C) 2016 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> This is free software; you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.). Please install a more recent version of Git.

### ISSUE THREAD

**Issue by Robin-zero** [gitkraken/vscode-gitlens#2099]
### GitLens Version

v12.1.2

### VS Code Version

Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

### Git Version

git version 2.37.1.windows.1

### Description

1. Open a project which has git control
2. Wait a minutes, then an error toast about git version

As follows is the toast content:
**GitLens requires a newer version of Git (>= 2.7.2) than is currently installed (GNU bash, version 4.4.23(1)-release (x86_64-pc-msys) Copyright (C) 2016 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> This is free software; you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.). Please install a more recent version of Git.**

### Logs, Screenshots, Screen Captures, etc

![image](https://user-images.githubusercontent.com/22169252/179720662-0523aa23-0ddb-4a9a-a884-16bff9366410.png)

**Comment by eamodio** [comment]
It looks like GitLens found something that looked like `git` but was bash instead. Do you have your `git.path` set in vscode to bash rather than Git? 

If not, can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ channel, and if its Git related please also attach the logs from the _GitLens (Git)_ channel.

Thank you!

**Comment by Robin-zero** [comment]
Thanks for your prompt, I have found the reason for the error, I set `git.bash` with wrong value like `E:\\ProgramFiles\\Git\\bin\\bash.exe`, the correct one should be `E:\\ProgramFiles\\Git\\bin\\git.exe`, forgive my carelessness. (╥╯^╰╥)
