### ISSUE TITLE
Search & Compare quickpick shouldn't select the mode text when opening

### ISSUE THREAD

**Issue by MohanVallivedu** [gitkraken/vscode-gitlens#2136]
Type: Feature Request

Hello team,
In the 'Source Control' section, when we go to SEARCH & COMPARE tile. and select any one of the options (Search for commits by 'message', 'author', etc..), it will open a dialog with text highlighted as "author: ". If we type something, it will replace the tag "author: " to our text which is not good.

![image](https://user-images.githubusercontent.com/53256123/182956505-cee2caab-0695-447c-ad4d-ca14b389d784.png)

![image](https://user-images.githubusercontent.com/53256123/182956537-44f41fef-8a79-4486-a7e8-2af34edc7074.png)

It would be good if the tag text is not highlighted/selected, so that we can start writing our text without removing the tag.
Thanks!

**GitLens**: v12.1.2
**VS Code**
Version: 1.70.0 (system setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by eamodio** [comment]
This one was trickier than I thought because VS Code doesn't let extensions control the selection in the quick picks (what that popup is called), but I found a workaround (setting the input text before the quick pick is shown causes VS Code to select the text, while updating the text after its shown leave it unselected.

Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by MohanVallivedu** [comment]
It is working well. Thank you for your quick response and the fix :)
