### ISSUE TITLE
version 2022.8.3105 is erroneously marked as the latest version in the marketplace

### ISSUE THREAD

**Issue by sheldonneuberger-sc** [gitkraken/vscode-gitlens#2229]
### Description

Run `curl -O https://eamodio.gallery.vsassets.io/_apis/public/gallery/publisher/eamodio/extension/gitlens/latest/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage`, unzip the file, and examine the extension/package.json.

Actual behavior: the version is 2022.8.3105.
Expected behavior: the version is the latest version (currently 12.2.2).

You can also click the Version History tab on https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens and it shows this.

### GitLens Version

12.2.2

**Comment by eamodio** [comment]
Yeah, unfortunately GitLens is in a bit of a not great spot on the marketplace right now since we tried to adopt the new VS Code pre-release support (but had to backtrack since it caused too many unintended side effects). We are working with the VS Code marketplace team to get it resolved.

**Comment by BryanAPEX** [comment]
I saw this is still opened so I wanted to ask if there's still issues going on with this behind the scenes?

When downloading the extension file from the [marketplace listing](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens), it appears to be serving the pre-release version. Yet installing from the extension panel inside VSCode correctly gives 14.0.1. I'm unclear why they would be sourced from two different places, but it's causing some issues with sourcing the extension in my enterprise environment. Is there a different and repeatable way to get the release vsix file from the marketplace?

**Comment by eamodio** [comment]
Unfortunately, there wasn't a way for the marketplace team to resolve this, until they fully handle "pre-release" versions like VS Code already does. And because we used a date-based version for pre-releases, they always show up as the "latest" version. We hoped we could backtrack on using the date-based versions, but the marketplace team would still have been unable to remove the existing date-based versions, so that would have left us in an even worse spot with a very old/expired pre-release as the "latest".

So until the marketplace adds support for pre-release versions (which is on their roadmap -- though sadly has been for a LONG time), there isn't a better option for us.
