### ISSUE TITLE
Commit Graph: allow to be moved to the Secondary Side Bar (and Primary Side Bar)

### ISSUE THREAD

**Issue by ericsampson** [gitkraken/vscode-gitlens#2311]
Hi, I'd love to be able to move the Commit Graph into the Secondary Side Bar, like you can with other gitlens views.
And/or be able to have it as its own Primary Side bar with an icon.

Thanks!

**Comment by eamodio** [comment]
Thanks for the suggestion. How would you like that to work? The side bars in general are often very narrow and I'm not sure the Graph in its current form would work well in that space. What would you like to see here?

**Comment by ericsampson** [comment]
I figured that my suggestion might be one of those "XY problem" scenarios lol.

The current mechanism of the commit graph being a tab alongside the open files doesn't work great for me--even if I pin the tab, that doesn't come up if I open up a new window. And that is super annoying--I want the Commit Graph to be always part of my IDE setup when I open a new window, and easily toggled like I can with a side bar.

I don't really love the how the Commit Graph is implemented using the document view--it feels like a kludge/mis-fit and gives it "second class citizen" Ux.

(I have an ultrawide monitor, so I would have no problem giving the Commit Graph enough space as a Secondary Side Bar :)

Does that make any sense?
Thanks for listening!

**Comment by xididri** [comment]
Could not agree more @ericsampson 

I don't use the Secondary Sidebar but I would love to have the Commit graph accessible with in the Primary Sidebar with a dedicated icon, especially since the existing Primary Sidebar Gitlens icon is useless.

It is true however that this would be very narrow for the Commit Graph, you might have a very wide screen but most users don't (I do have a very wide screen but use it to place 2 windows in it). Hence the Commit Graph view would need to be reworked so it can be used in a 250px or so wide view.

**Comment by eamodio** [comment]
This has been possible for a while now so closing this.

**Comment by hungify2022** [comment]
Move to the tab bar rather than the panel bar.
