### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by AurevoirXavier** [gitkraken/vscode-gitlens#2389]
### Description

1. Open vscode.
2. Run gitlens+: show commit graph.
3. vscode freeze.

Other vscode graph utility also faces this problem.

https://github.com/mhutchie/vscode-git-graph/issues/712

This happens randomly, not happens every time.

### GitLens Version

13.1.0

### VS Code Version

Version: 1.75.0-insider
Commit: 250a8f36c93721830b0ef2e39dc065d6944d9912
Date: 2022-12-12T05:36:38.306Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: Yes

---

I also tested this on the latest stable vscode.

### Logs, Screenshots, Screen Captures, etc

<img width="771" alt="image" src="https://user-images.githubusercontent.com/16152305/206976896-42783363-9b3c-424d-8714-40bf572f4cef.png">

**Comment by eamodio** [comment]
We've had other reports of VS Code webviews (the GitLens Graph, GitGraph are webviews) causing VS Code to freeze up, but they have gone away for other users when upgrading VS Code (though you are on 1.75-insider). I think this is an electron issue at its core, since any webviews seem to be able to cause it for affected users.

Do you see it freeze up if you show the GitLens: Open Settings page?

Can you please file this on the VS Code repository? Especially as it isn't a GitLens only thing.
