### ISSUE TITLE
Limited time trial starts on its own without direct user interaction

### ISSUE THREAD

**Issue by MarioLiebisch** [gitkraken/vscode-gitlens#2405]
### Description

Yesterday I learned there's GitLens+, which I've never noticed before (I'm mostly using GitLens for the inline commit details after all), but after trying to find out what "local repository" even means (btw. I consider this wording rather vague/misleading anyway "local repository" for me would be anything in my filesystem, remotes or not), I'm already on the free trial without me specifically signing up for any trial or requesting to start the trial period (even if it's without an account).

So instead of giving me time to explore on my own leisure, I feel forced into this, losing 2 out of 3 days on a weekend.

This shouldn't ever happend and to be fair it's already turning me off to ever consider looking at this again. I hate programs/websites doing this. The Welcome page had clear "Start Trial" buttons, that's fine. But it still just started it on its own anyway, just because I opened a non-GitHub repository with remotes (and the graph opened from Command Palette). I'd prefer it showing a symbolic blurry view with a banner and a button, first (or something similar).

### GitLens Version

13

### VS Code Version

Version: 1.75.0-insider (system setup)
Commit: 11238faea62d570d77afe6edfe05c8b732c44a2b
Datum: 2022-12-13T05:22:12.417Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
Betriebssystem: Windows_NT x64 10.0.22621
Sandkasten: Yes

### Git Version

git version 2.38.1.windows.1

### Logs, Screenshots, Screen Captures, etc

I haven't touched any addon settings for months, so if you want to review any values set, let me know.

**Comment by kpocius** [comment]
To make it worse, the extension seems to ignore `"gitlens.plusFeatures.enabled": false` setting, which is super annoying.

**Comment by wojtekxtx** [comment]
Ive noticed this also.
I reckon they (team) started to force paid version upon users. Thats bad. Way too bad.

**Comment by MarioLiebisch** [comment]
Allowing people to use bonus/paid features for free in public repositories is certainly great, it's just off to be forced into the trial for other repos.

**Comment by eamodio** [comment]
@MarioLiebisch Thank you for your feedback and we are definitely listening to how we can improve here. And I'm really sorry you felt that undue pressure because of the trial time limit -- that is FAR from the desired intent.

When we came out with the Commit Graph in GitLens 13, we really wanted everyone to be able to experience it without having an initial gate in front of it. So, we first removed the need for an account for local-only (no remotes) and publicly hosted repositories to allow those users to experience the Commit Graph and all other GitLens+ features without any gates at all. Then we really wanted users with privately hosted repositories to also experience the Commit Graph without that initial gate as well, so we decided to experiment with auto-starting the no-account portion of the trial for the Commit Graph (we didn't remove the initial trial-start gate on the other GL+ features).

We did consider that auto-starting the trial might cause concern with some users but thought the benefits might out-weigh that and was worth experimenting with. We are also thinking a lot about trials and how we can improve them going forward, and we will probably start experimenting with other options in the near-ish future, e.g. time-trial per "active" day rather than clock time, time-trial per feature, usage-based trial per feature, time-trial for full feature-set but limited after trial is over. Those are just some of the ideas here and we would love to hear feedback as what you all would like to see -- with the acknowledgement that we have to monetize these features in some way for some audience to keep our investments in GitLens sustainable.

@kpocius Unless there is a bug (and please open a new issue if so), we aren't ignoring `"gitlens.plusFeatures.enabled": false`. We did change the behavior to adapt to the change in the local/public access above, because why would we hide features you have full access to.

@wojtekxtx To be completely clear, there is no paid version of GitLens, and we are definitely NOT forcing that on anyone. We've just added some new COMPLETELY optional features, in addition to all the always free features that require a paid subscription for use on privately hosted repositories. We even provide multiple ways to hide the GitLens+ features if you really don't want to see them, e.g. the "Hide GitLens+ Features" link on the Home view (though looks like there is a bug where that is not showing in certain cases), a Hide GitLens+ Features command in the command palette, and the `gitlens.plusFeatures.enabled` setting which can be synchronized between machines (FYI, the link and command, just set the setting for you).

I hope that helps provide some context and definitely look forward to your feedback. Thank you!

**Comment by eamodio** [comment]
Specifically on the auto-started time trial -- what do you all think about the trial being 3 "active" days, rather than 3 calendar days, where an "active" day could be you "used" a GitLens+ feature at any point in that calendar day. So if the trial started on Friday, and you didn't come back to try/use any GL+ features until a week later, you'd still have 2 more active days before it would expires.

Thoughts?

**Comment by MarioLiebisch** [comment]
No worries, I don't think any of this was done/implemented in ill-intent. You guys want to make some money off this after all. A happy customer is a paying customer.🙂

But back to that idea:
I'm not sure, this is overall very tricky. I certainly understand the idea of showing everything off right away without extra interactions etc.

But just as a random brainstorming idea:

* For local-only and public repositories there's no change, i.e. the existing behavior.
* For repositories that are detected to have non-public remotes (i.e. those requiring a subscription),  instead of auto-starting the trial (or showing nothing at all) only show the latest 5 or maybe 10 commits (or the commits from last 24-48 hours) and use the free space below to openly explain to the user why this is the case, plus ask them on whether they'd be interest in starting a trial or purchase a license for this feature.
* The very same strategy could work for other GitLens+ features such as the history/heat map.

In my opinion, this would have quite a few advantages:

* There's no immediate pressure or time limit.
* Users can always see how the feature would look like with their actual repository data. This sounds like a great opportunity at a "light" demo. (I guess one could always do this by removing the remotes, but that feels cumbersome)
* Users always see how or why the feature is suddenly gone (imagine someone adding a remote after a few days of working on a brand new project that's local only at first or why they'd suddenly need a subscription like 3 days later, potentially having forgotten about adding the remote triggering this).

**Comment by wojtekxtx** [comment]
@eamodio are you, by any chance, working in marketing dept? Your whole story is just pile of nonsensical marketing oriented BS. Nothing more. Sorry.

Setting command `gitlens.plusFeatures.enabled` to `false` does exactly **nothing**. Its just to fool users that sth is disabled where in reality its not.

This only proves that I have done right thing with looking for alternative.

> I don't think any of this was done/implemented in ill-intent.

@MarioLiebisch just the opposite......

**Comment by d13** [comment]
@kpocius @wojtekxtx 

[I've created this issue](https://github.com/gitkraken/vscode-gitlens/issues/2407) to capture the bug regarding the `gitlens.plusFeatures.enabled` setting. Feel free to provide details there about what is not working for you. I will be testing this feature as well and making adjustments. Thanks.

**Comment by wojtekxtx** [comment]
@d13 There is not much details we can provide. BTW, dont be so protective towards makers of GitLens.

**Comment by WolfspiritM** [comment]
I'd prefer to not have a trial at all. I'm currently setting up a workspace "default" for new users and it's actually annoying that new users would see features that they can't use after 3 days. I'm currently not going to install gitlens per default cause of that. I tried setting gitlens.plusFeatures.enabled to false but that doesn't hide plus features for that inital 3 days.

**Comment by GottZ** [comment]
lol. i came here expecting to find issues in regards to the trial, and what I got was the reverse of my problem of actually paying but not being recognized as licensed.
![image](https://github.com/gitkraken/vscode-gitlens/assets/559564/93a30939-6d16-4d94-9c57-7148d6db208b)
![image](https://github.com/gitkraken/vscode-gitlens/assets/559564/2f6314c0-2cc8-46f1-bda5-51d9f37f1cc7)

**Comment by jkelroy** [comment]
@GottZ I see your email as well. It looks like your subscription is in an unexpected state and I am having the team take a look into it now.

**Comment by GottZ** [comment]
> @GottZ I see your email as well. It looks like your subscription is in an unexpected state and I am having the team take a look into it now.

thank you. apparently I could pinpoint out, that the gitlense subscription backend service processes my account state differently than the other applications.
(even the cloud tools work fine)
![GIzGDnnWwAAVpab](https://github.com/gitkraken/vscode-gitlens/assets/559564/ba423181-5985-4fa0-b634-53208e615074)

**Comment by jkelroy** [comment]
@GottZ I sent a follow up over email - the issue with your subscription was fixed and you should be seeing Pro in GitLens now. If not, try [signing into GitLens](https://help.gitkraken.com/gitlens/gitlens-faq/#how-do-i-sign-in-or-out-of-gitlens) again.

**Comment by LoganDark** [comment]
The thing started some trial automatically without asking me. It asked me if I wanted to start my 7-day trial and it said no. But now there is something in the bottom bar saying I have 2 days left of my 3-day trial anyway. How do I turn this off / end this / undo this? I don't want the trial. In fact I'd rather not even see features I don't have access to.

**Comment by Lurchicus** [comment]
Auto installing software annoys me. I uninstalled gitlens. I may look at it some other time (when it's truly volentary).

**Comment by eamodio** [comment]
Really not sure what you are talking about as GitLens doesn't auto-install anything. This issue is about an auto-start of a preview of the commit graph when you accessed it for the first time. And that hasn't been the case since the May release, where you explicitly have to click a Continue button to start the preview.
