### ISSUE TITLE
Opening GitLens settings freezes VS Code

### ISSUE THREAD

**Issue by CTimmerman** [gitkraken/vscode-gitlens#2452]
### Description

1. Open GitLens Settings via the Command Palette
2. Try to disable "Current Line Blame".
3. Find VS Code not responding even after force quit, restart, and reinstalling GitLens as only extension.

### GitLens Version

13.2.0

### VS Code Version

1.74.3 (Universal)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:07:18.579Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No

### Git Version

git version 2.37.1 (Apple Git-137.1)

### Logs, Screenshots, Screen Captures, etc
Looks like a memory leaking loop as MacOS just prompted me to kill 70+ GB VS Code.

**Comment by raoulkent** [comment]
I've come to the same conclusion after having issues with VS Code hanging after leaking memory like described by @CTimmerman.
Also running MacOS ARM.

**Comment by eamodio** [comment]
This looks like another case of https://github.com/gitkraken/vscode-gitlens/issues/2272 which feels like a VS Code issue, since others reported that it happened with any GitLens webview (and also webviews from other extensions). And as far as I know the issues for other sort of just resolved themselves -- either miraculously or after a GitLens or VS Code re-install.

Could you try to install the Insiders version of VS Code to see if you see the same behavior or maybe try re-installing VS Code or even GitLens?

**Comment by CTimmerman** [comment]
Indeed it works fine in a later stable version of VS Code:

Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z (5 days ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
