### ISSUE TITLE
The experience of viewing file changes is poor in commit graph 

### ISSUE THREAD

**Issue by pavlelee** [gitkraken/vscode-gitlens#2537]
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/5382358/222692376-aecfe4c0-e60f-4b52-976b-705b9d903036.png">

The questions are as follows：
1. After clicking on commit, the details displayed are very small.
2. Click on the file to view the difference. The difference page is very small.
3. To continuously view the changes of different submitted files, you must first unpin

You can refer to the same type plug-in Git Graph
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/5382358/222693311-0bda23f9-71df-4d07-810f-ba74f6b355d1.png">

Click on the file to view the difference, will be displayed all over the screen.
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/5382358/222693735-ebf5e0dc-c5be-4669-b007-0453743f1867.png">

**Comment by eamodio** [comment]
@pavlelee Thanks for the feedback!

> After clicking on commit, the details displayed are very small.

The best option here, is to drag the Commit Details view into its own sidebar or better yet drag it all the way to the right side and drop it into the Secondary Sidebar.
We are discussing putting the Commit Details view into its own sidebar by default -- but unfortunately, we can't automatically add it to the Secondary Sidebar (VS Code doesn't allow extensions to place things there by default yet)

> Click on the file to view the difference. The difference page is very small.

We are looking at adding some better options here -- how would you want this to work? Would you want the diff to hide the Graph and open the diff in the same group? Or open it below the Graph rather than to the right?

> To continuously view the changes of different submitted files, you must first unpin

This should now be resolved in the latest pre-release edition of GitLens and will be coming soon to the stable GitLens release.

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

Hope that helps!

**Comment by pavlelee** [comment]
The interactive experience of the new version is even worse. First of all, I want to see the `commit graph`. Content should focus on the whole page, not split right, which will not be the case in the previous version, which is degraded.
![image](https://user-images.githubusercontent.com/5382358/228447040-72e9bf6f-2228-466c-b710-a281458abdcb.png)

> The best option here, is to drag the Commit Details view into its own sidebar or better yet drag it all the way to the right side and drop it into the Secondary Sidebar.
We are discussing putting the Commit Details view into its own sidebar by default -- but unfortunately, we can't automatically add it to the Secondary Sidebar (VS Code doesn't allow extensions to place things there by default yet)

The visual experience will be better this way, but the linkage is too poor. Clicking commit will not automatically pop up sidebar, and closing Commit Graph will not close sidebar.
![image](https://user-images.githubusercontent.com/5382358/228447916-8302e1b7-9768-43fe-9500-eb6c1c65cd7b.png)

> We are looking at adding some better options here -- how would you want this to work? Would you want the diff to hide the Graph and open the diff in the same group? Or open it below the Graph rather than to the right?

Diff view generally has a lot of content, so it's best to show it on the full page instead of split right. It's more practical.

**Comment by pavlelee** [comment]
This barely meets my interaction needs.
![image](https://user-images.githubusercontent.com/5382358/228453138-acc3a35d-d809-48bf-81d8-da7dfb430f78.png)

**Comment by eamodio** [comment]
FYI, https://github.com/gitkraken/vscode-gitlens/issues/2602 has landed in pre-release which could be a good alternative to help with this.

But the latest pre-release has further improvements as well. We now will open the diffs in the active editor group, rather than in a new group on the side. We will eventually be looking into further possibilities with some new APIs in VS Code.

**Comment by pavlelee** [comment]
@eamodio  `"gitlens.graph.layout": "panel"` This solution has satisfied the usage habit, and such a fast response speed makes me more confident in the pro version.
![image](https://user-images.githubusercontent.com/5382358/229008836-3139a6d2-8c02-46d8-9539-19fd8ae9f88a.png)

**Comment by pavlelee** [comment]
@eamodio  I found new bug, it's not work
<img width="1765" alt="image" src="https://user-images.githubusercontent.com/5382358/229668530-4e79a283-d004-4c25-9175-1a69391161f8.png">

**Comment by eamodio** [comment]
@pavlelee Doh, that's good catch -- that is fixed by https://github.com/gitkraken/vscode-gitlens/commit/2aace4b57293d09b149782ca162b7130a7d48737. Will be out in tomorrow's pre-release.

Can you provide more actionable feedback with the `editor` layout to see what we can improve? While we may have limited options to the control VS Code allows extensions, we definitely want to see what we can still do.

**Comment by pavlelee** [comment]
@eamodio `v2023.4.505` version already satisfy the usage habit In the `editor` layout, But the commit detail will not be closed when the graph is close. and the experience is poor if not drag it to the right side, this had better be used out of the box.

<img width="1785" alt="image" src="https://user-images.githubusercontent.com/5382358/230116670-eb9ba78b-5152-420a-a3b6-2d7a9636c555.png">
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/5382358/230117829-2b2d64ac-fbf4-4a8a-9353-9f68f7bc6a2a.png">

**Comment by eamodio** [comment]
Thanks -- yeah, we would LOVE to move the Commit Details to the secondary side bar by default but VS Code doesn't allow it yet. You can vote on that feature here: https://github.com/microsoft/vscode/issues/151681

**Comment by pavlelee** [comment]
@eamodio another issue is if project have a lot of branches, when I develop on my branch, I want to see other branch history must switch to it, this is very trouble.

<img width="1783" alt="image" src="https://user-images.githubusercontent.com/5382358/230120448-159963d6-1fd8-444f-a7f2-f5059c149d1a.png">

**Comment by eamodio** [comment]
@pavlelee You can just set it back to Show All Local Branches (which is the default)

**Comment by pavlelee** [comment]
> @pavlelee You can just set it back to Show All Local Branches (which is the default)

Coincidentally, most of the scenes I mentioned are remote branches.

**Comment by pavlelee** [comment]
> Thanks -- yeah, we would LOVE to move the Commit Details to the secondary side bar by default but VS Code doesn't allow it yet. You can vote on that feature here: [microsoft/vscode#151681](https://github.com/microsoft/vscode/issues/151681)

I will vote, but I think `panel` are already fine, do you still need so many options?

**Comment by eamodio** [comment]
> Coincidentally, most of the scenes I mentioned are remote branches.

The "Show All Local Branches" option is kind of misnamed, and we will change it to "Show All Branches" to be clearer. That first option is to choose between showing "all" branches or only the current branch, and the "Hide *" options further refine what should be shown.

**Comment by eamodio** [comment]
Closing this as we've added lots of improvements here and the new panel layout: https://github.com/gitkraken/vscode-gitlens/issues/2602
