### ISSUE TITLE
Allow disabling "Open worktree for pull request via GitLens..." from repository context menu

### ISSUE THREAD

**Issue by benatshippabo** [gitkraken/vscode-gitlens#2597]
## Description

Currently you are able to configure which context menu items show up in GitLens except for "Open worktree for pull request via GitLens"

https://github.com/gitkraken/vscode-gitlens/blob/01f92d218e3445858fb912cd375b8bcd501df4b6/package.json#L5806-L5811

It is very annoying since it occupies the top spot, muscle memory has many users clicking that instead of "Checkout Pull Request"

![image](https://user-images.githubusercontent.com/66273043/227072854-e75e0175-a5c4-4dda-a76d-8a4929e04fda.png)

## Expected behavior

Users are able to toggle off "Open worktree for pull request via GitLens..." from the context menu to clean up their context menu

![image](https://user-images.githubusercontent.com/66273043/227073164-138dd879-d867-4556-b281-100206af3a87.png)

**Comment by eamodio** [comment]
The first issue of it being in the wrong spot should now be fixed with the latest version of the GitHub PR & Issues extension (since they moved their menu positions around).

I've also added a new setting to toggle this menu, which should be in tomorrow's (v2023.4.06XX) pre-release edition of GitLens.

If you want to check it out, you can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)
