### ISSUE TITLE
Gitlens doesn't show repositories in a tree folder structure

### ISSUE THREAD

**Issue by jayb1212** [gitkraken/vscode-gitlens#2656]
### Description

I have a git-tree folder, which has sub-folders representing various repositories. These don't show up in gitlens.

### GitLens Version

 13.5

### VS Code Version

Version: 1.77.3 (Universal)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:19:37.325Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes

### Git Version

2.39.2 (Apple Git-143)

**Comment by jayb1212** [comment]
![image](https://user-images.githubusercontent.com/112116493/235154441-f899790b-b378-4f83-87d1-9296bb0e2b27.png)

![image](https://user-images.githubusercontent.com/112116493/235154937-c678e539-07a5-45be-98dd-f2859c32b264.png)

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!
