### ISSUE TITLE
Gitlens not working with wsl terminal

### ISSUE THREAD

**Issue by anaclaraddias** [gitkraken/vscode-gitlens#2666]
### Description

My gitlens doesn't work when i'm using the wsl terminal (with the project inside it). In other projects at another terminal the gitlens works as the usual.
I tried to install the gitlens again but didn't work, and the entire connection with git is working normally.

### GitLens Version

13.5.0

### VS Code Version

Version: 1.78.1 (user setup)
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Date: 2023-05-04T09:48:08.683Z
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

![Captura de tela 2023-05-10 121945](https://github.com/gitkraken/vscode-gitlens/assets/101477705/f284ba08-b671-4b71-83b3-2d02c42a1816)

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by anaclaraddias** [comment]
In other projects where the gitlens is working (with a bash terminal) all the changes I make in the code are displayed visually, in addition to presenting the current branch I am within VS Code (like the different types of colors and the display at source control, where I can make changes and visualize it). With the WSL terminal, it seems like gitlens doesn't recognize the Git-related information.
