### ISSUE TITLE
Using invalid Git path with Git Bash as terminal on Windows

### ISSUE THREAD

**Issue by andriyDev** [gitkraken/vscode-gitlens#2695]
### Description

I am on Windows, using Git Bash as my terminal. I even switched the integrated terminal in VSCode to use Git Bash instead.

Ever since 13.6.0, I can no longer run many of the GitLens functions, since they all now pass an explicit executable to Git, instead of just calling "git" directly. What I mean is, if I try to create a branch for example, GitLens tries to run `D:\Programs\Git\cmd\git.exe -C "<my_repo>" -c "core.editor=code --wait --reuse-window" branch test main`. Since I'm using Git Bash though, the path should use forward slashes instead of back slashes.

I tested this in 13.5.0 and the correct command `git -C "<my_repo>" -c "core.editor=code --wait --reuse-window" branch test main` is printed. I also tried manually setting my Git path using the `git.path` setting but it looks like GitLens ignores this setting.

This does work if I change my terminal back to the default (Powershell), but this isn't worth it for me. I wonder if its possible for the path to just always be forward slashed and hope Windows always handles it well, although I understand that's quite the hack.

### GitLens Version

13.6.0

### VS Code Version

Version: 1.78.2 (system setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

### Git Version

git version 2.31.1.windows.1

**Comment by elldawg** [comment]
Seeing the same issue

**Comment by jkelroy** [comment]
Hello @andriyDev and @elldawg, can you please see if this issue is still reproducible in the pre-release edition of GitLens?​ You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/27739784/240437025-f9f6b0cf-cda3-4b53-973b-3689f1e4481a.png)

If so, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by andriyDev** [comment]
Ah yes, it looks like this is fixed in the pre-release version (at least for me). I guess this can be marked as closed @jkelroy?

**Comment by elldawg** [comment]
> Ah yes, it looks like this is fixed in the pre-release version (at least for me). I guess this can be marked as closed @jkelroy?

@jkelroy pre-release also works for me
