### ISSUE TITLE
GitLens doesn't detect the repository when used on github.dev

### ISSUE THREAD

**Issue by busybox11** [gitkraken/vscode-gitlens#2703]
### Description

I installed GitLens inside of a temporary github.dev VSCode environment, and it doesn't detect the repo that I'm in.
Clicking on the "Open a Folder or Repository" buttons only redirects to the file tree view and does not do anything else.

![image](https://github.com/gitkraken/vscode-gitlens/assets/29630035/e83e44ed-6b1e-4b06-b605-cfce83b054c5)

### GitLens Version

v13.6.0

### VS Code Version

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:41:12.581Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### Git Version

🤷

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/29630035/61a6d717-1340-4106-a71d-8f613badaf5d)

Version control is working natively in VSCode, I can see my branches and access the native version control tab.

**Comment by eamodio** [comment]
Can you please see if this issue is still reproducible in the pre-release edition of GitLens? Thanks!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by busybox11** [comment]
Does it?
