### ISSUE TITLE
eamodio.gitlens tried to set the view size of gitlens.views.contributors but it was ignored because the view container does not belong to it

### ISSUE THREAD

**Issue by ulugbekna** [gitkraken/vscode-gitlens#2724]
### Description

I see this warning in the chrome dev tools console when I open vscode insiders: 

```
WARN eamodio.gitlens tried to set the view size of gitlens.views.contributors but it was ignored because the view container does not belong to it
```

### GitLens Version

v2023.6.805

### VS Code Version

Version: 1.79.0-insider
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:33:06.501Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

### Git Version

git version 2.39.2 (Apple Git-143)

**Comment by jkelroy** [comment]
Hello @ulugbekna, I did see this issue in v2023.6.805, but it does not appear anymore in the latest pre-release (v2023.6.1912). Can you please see if this issue is still reproducible in the latest pre-release of GitLens?​

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/27739784/240437025-f9f6b0cf-cda3-4b53-973b-3689f1e4481a.png)

**Comment by ulugbekna** [comment]
seems fixed indeed
