### ISSUE TITLE
run

### ISSUE THREAD

**Issue by Solomonkassa** [gitkraken/vscode-gitlens#2752]
### Description

it is not running

### GitLens Version

12.0.0

**Comment by jkelroy** [comment]
Hello @Solomonkassa, this is caused by version 12.0 requiring an extension (gitkraken.gitkraken-authentication) that is no longer available. However, you can upgrade to a more recent version - I would recommend the latest - where you should not see any issues. 

![Screenshot 2023-06-19 at 3 02 47 PM](https://github.com/gitkraken/vscode-gitlens/assets/27739784/b7feee05-2de8-4ec4-8988-d6c51cc9f88a)
