### ISSUE TITLE
GitLens Inspect "File history" is missing entries after "git mv"

### ISSUE THREAD

**Issue by agobeaux** [gitkraken/vscode-gitlens#2828]
### Description

I cannot share the repository or a screenshot of the repository, but steps are easily reproducible.
If a file `a.txt` was renamed to `b.txt` using `git mv a.txt b.txt`, the file history of GitLens inspect will not show the full history, only the history of `b.txt`.
However, when looking at the line history, the full history is there (`a.txt` + `b.txt`).

Steps to reproduce:
- Checkout any repository
- Do a `git mv` command on any file
- Make a commit containing the renaming
- Check the line and file history of the new file

### GitLens Version

14.1.1

### VS Code Version

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (2 mos ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0

### Git Version

git version 2.40.1

**Comment by Jollus174** [comment]
I can confirm this is happening on my machine as well.

### GitLens Version
14.2.0

### VS Code Version
Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version
2.41.0

![image](https://github.com/gitkraken/vscode-gitlens/assets/30223207/5c33dc66-302e-474e-a207-69bfd1e33829)

The **Toggle Follow Renames** option is also disabled is my VS Code.
![image](https://github.com/gitkraken/vscode-gitlens/assets/30223207/4a544346-213e-42a4-8705-7ea51cb6ce75)

The **git blame** option does seem to show line changes, but it no longer seems possible to follow File History renames in the left-side window.
![image](https://github.com/gitkraken/vscode-gitlens/assets/30223207/42c69b89-8110-4b0e-8d76-56a0f41ebe4d)

**Comment by Jollus174** [comment]
Actually, I think I've figured it out. After making sure that this is set to `Toggle Filter: All Branches`, then `Follow Renames` is enabled once more and renamed files once again come up in the left-side window.
![image](https://github.com/gitkraken/vscode-gitlens/assets/30223207/0265e8cc-0a29-43da-af5c-e97bd395b519)
![image](https://github.com/gitkraken/vscode-gitlens/assets/30223207/d22cfe39-0740-4a19-9760-a4afc41b9602)

**Comment by ili101** [comment]
Setting `Toggle Filter: All Branches` I only get commits down until the last merge (so if I'm on master I see only down until the last "fix" branch merge).
And as you mentioned without it the option is unavailable.
Workaround is to use other extension like "Git History" or simply do `git log --follow ./path/to/file`

**Comment by eamodio** [comment]
Since it looks like newer version of Git now support the `--all` flag in conjunction with `--follow`, I've removed that limitation in GitLens, and you can now choose to show the history for all branches while still following renames.

We've also changed some defaults and added a new options (and renamed others) to the _File History_ view in the latest pre-release edition of GitLens. We now follow renames by default, which you can still toggle it on/off, and we hide merge commits by default, which can also be toggled it on/off.

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/f0c04c64-f158-479f-8afc-5d3b5946fcae)

Can you please verify this fix in tomorrow's (`v2023.10.13xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by axosoft-ramint** [comment]
Verified fix using repro steps in the original post.

**Comment by Jollus174** [comment]
Also verified here. The options are much more clear now as well, thanks for that! This also resolves another small issue I was having where merge commits would always show up in the File History. 🎉
![image](https://github.com/gitkraken/vscode-gitlens/assets/30223207/d01fefc5-8ca1-4e7d-a6b8-7938db356caa)

**Comment by Dew0Tgx** [comment]
great
thank you so much

Op za 14 okt 2023 om 04:01 schreef Joel Sweetman ***@***.***>
