### ISSUE TITLE
gitlens.currentLine.enabled doesn't work

### ISSUE THREAD

**Issue by icetbr** [gitkraken/vscode-gitlens#2829]
### Description

I add/remove it, it makes no difference. Toggle Line Blame works, but it resets when the window is reloaded.

I tried uninstalling the extension, and switched to pre-release and back.

My global settings.json (there is no local settings.json)
```json
 "gitlens.currentLine.enabled": false,
 "gitlens.currentLine.uncommittedChangesFormat": ""
```

### GitLens Version

v2023.7.2105

### VS Code Version

Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:25.257Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-76-generic

### Git Version

2.34.1

**Comment by eamodio** [comment]
Sorry for the long delay here, can you please see if this issue is still reproducible in the pre-release edition of GitLens? Thanks!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

And if it is reproducible, can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by icetbr** [comment]
Sorry for the delay as well. I switched to the pre relase version. My whole team, 7 devs, also have the same problem. I assumed it was a known bug.

It is reproducible. I started VsCode after having toggled line blame off. Then I toggle it on. Here are the logs.

[gitlens.txt](https://github.com/gitkraken/vscode-gitlens/files/13696202/gitlens.txt)
[gitlensGit.txt](https://github.com/gitkraken/vscode-gitlens/files/13696203/gitlensGit.txt)

**Comment by icetbr** [comment]
Sorry for the late reply, I found the problem. I'm not sure what this does, but removing the 2nd line worked.
```js
{
    "gitlens.currentLine.enabled"                 : false,
    "gitlens.mode.active"                         : "review",
}
```

**Comment by eamodio** [comment]
@icetbr Thanks for the extra info -- that makes this expected behavior. GitLens has 2 built-in modes, Zen and Review, Zen disables a lot of settings, while Review enables them -- you can also create custom modes. See https://help.gitkraken.com/gitlens/gitlens-features/#modes. You at some point have put GitLens into "review" mode, which is enabling the current line settings.
