### ISSUE TITLE
File history missing commits after Git Interactive Rebase

### ISSUE THREAD

**Issue by symisz** [gitkraken/vscode-gitlens#2843]
### Description

After doing an interactive rebase with Gitlens, i notice a commit being absent in the file history panel.

As seen here my fourth commit is just not there anymore.
![image](https://github.com/gitkraken/vscode-gitlens/assets/32195791/d8a5ac43-81f0-4121-9bf8-ef051b59586b)

although i did made it and it exist here:
![image](https://github.com/gitkraken/vscode-gitlens/assets/32195791/8e741b99-252c-4010-9156-2c0b719a4e30)
and here
![image](https://github.com/gitkraken/vscode-gitlens/assets/32195791/22cd06bb-01d5-4257-85c9-16f4c6e66408)

### GitLens Version

14.1.1

### VS Code Version

Version: 1.80.2 (system setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22631

### Git Version

git version 2.25.1

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and the detailed steps to reproduce it?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by symisz** [comment]
I have not been able to reproduce this error, i'll reopen this case when i do stumble on it again.
