### ISSUE TITLE
Can't use Azure OpenAI model because i can't save the openai key because of the verification

### ISSUE THREAD

**Issue by Yousr-Ahmed** [gitkraken/vscode-gitlens#2940]
### Description

1- i opened the settings of the extension 
2- Specifies a custom URL to use for access to an OpenAI model via Azure
3- go to commit 
4- press Generate commit messege
5- enter azure api key eg. 5e421409dd124cb081151965d2fd835e
6- error "Please enter a valid OpenAl API key"

excepted to pass the verification 

### GitLens Version

14.3.0

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/117375769/39504e0c-d9e6-4964-bdda-31daf8484248)
![image](https://github.com/gitkraken/vscode-gitlens/assets/117375769/bc295396-40ff-42fb-a07e-0573df00192c)

**Comment by Yousr-Ahmed** [comment]
this code may be related 
https://github.com/gitkraken/vscode-gitlens/blob/9b83093848050246b9445d530fd3a28197d08365/src/ai/openaiProvider.ts#L177

**Comment by Yousr-Ahmed** [comment]
and this
https://github.com/gitkraken/vscode-gitlens/blob/9b83093848050246b9445d530fd3a28197d08365/src/ai/openaiProvider.ts#L185C7-L185C7

**Comment by Yousr-Ahmed** [comment]
@eamodio

**Comment by Yousr-Ahmed** [comment]
now i can enter the API key but i got Error: "Unable to generate commit message: (OpenAI:401) Unauthorized"

**Comment by Yousr-Ahmed** [comment]
https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/chat/completions?api-version={api-version}
i specifed the custom url from the pevious url

**Comment by Yousr-Ahmed** [comment]
@eamodio

**Comment by Yousr-Ahmed** [comment]
![image](https://github.com/gitkraken/vscode-gitlens/assets/117375769/bd7e46f7-9b09-4b8e-bfc5-8caa76f08688)
I copied the endpoint link from this

**Comment by eamodio** [comment]
@Yousr-Ahmed Is the URL you are using with all the pieces embedded in it -- e.g. `deployment-id` and `api-version`? If so, I'm not sure why you'd get a 401 -- we are providing the API key as the bearer token as the Azure client seems to do.

**Comment by ncx-kevinCefalu** [comment]
I can confirm that I'm getting the same results on v2023.9.2805 of the extension.

I've verified the URL is in the expected format, but I believe the issue is actually in the usage of the `Authorization` header. Documentation for Azure OpenAI suggests `api-key: YOUR_API_KEY` should be sent for API key authorization, rather than `Authorization: Bearer YOUR_API_KEY` like OpenAI expects. The `Authorization` header is supposed to be used to authorize using an Azure AD access token.

- [src/ai/openaiProvider.ts#L136](https://github.com/gitkraken/vscode-gitlens/blob/e89cc507b793a3b7782f874fe4b4d0e23c0ceab0/src/ai/openaiProvider.ts#L136)
- [Authentication | Azure OpenAI Service REST API reference](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#authentication)

![image](https://github.com/gitkraken/vscode-gitlens/assets/47864147/3925dc71-1ba1-472a-8c79-c9ba17576249)
![image](https://github.com/gitkraken/vscode-gitlens/assets/47864147/469980df-1f75-422a-94b3-e2bf682a5899)

**Comment by eamodio** [comment]
@ncx-kevinCefalu Thanks, in tomorrow's pre-release I've switched the auth for azure to use the `api-key` header -- please let me know if this fixes things for you all. Thanks!

**Comment by ncx-kevinCefalu** [comment]
@eamodio you nailed it! Well done, and thank you very much for your prompt response!

**Comment by Yousr-Ahmed** [comment]
@eamodio Thanks, I can confirm it's working now in v2023.10.105
