### ISSUE TITLE
Allow "File Changes" annotation to be enabled all the time

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [gitkraken/vscode-gitlens#3016]
at some point NLT Febuary 2023, the file changes view got changed so it's disabled when pressing ESC.

discussion https://github.com/gitkraken/vscode-gitlens/discussions/2490 brought this up but went unanswered.

I like it enabled all the time. I use vim keybindings so i press ESC constantly. There appears to be no way to change they keybind.

**Comment by eamodio** [comment]
Part of this ask was keeping annotations enabled all the time (see also #1988), which is now in the current pre-release of GitLens. There is now a new experimental setting that can be enabled to provide this behavior. Set `"gitlens.experimental.allowAnnotationsWhenDirty": true` to enable this new behavior, and now file annotations (blame, heatmap, changes) will be more persistent rather than going away on an edit. That setting also works in tandem with the existing `gitlens.advanced.blame.delayAfterEdit` which defaults to 5s -- which means after an edit it will take 5s before the annotations are recomputed. Lowering that will improve responsiveness but increase the performance overhead.

Let me know what you think of the new behavior. Thanks!

Still looking at addressing the keyboard shortcut dismissal.

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by eamodio** [comment]
In tomorrow's (`v2023.12.15xx`) pre-release edition of GitLens, we've added a `gitlens.fileAnnotations.dismissOnEscape` setting that can be set to `false` to stop the `ESC` key from dismissing the active file annotations.

**Comment by axosoft-ramint** [comment]
Verified in the current pre-release
