### ISSUE TITLE
 "file changed" bar disappear when turn on filter by author

### ISSUE THREAD

**Issue by laohubb** [gitkraken/vscode-gitlens#3042]
### Description

when open filter commits by author on git compare,the "file changed" bar will disappear

### GitLens Version

14.5.2

### VS Code Version

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.33.0.windows.2

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/26958703/9a7f0635-a575-4cc0-8de2-1e0522b86009)

**Comment by eamodio** [comment]
Unfortunately that is by-design, because there isn't a way to show a unified diff between commits without including all commits in the range. So we can't show an over all files changed list.

Technically we could show a "filtered" list, by showing just the unique set of files in all the filtered commits, but even so the diffs would (could) be wrong as it would be the diff between the 2 refs regardless of filtering.
