### ISSUE TITLE
Connection to GitHub Enterprise stopped working in 14.6.0

### ISSUE THREAD

**Issue by zuranthus** [gitkraken/vscode-gitlens#3069]
### Description

I have configured an enterprise github remote in gitlens
```json
   "gitlens.integrations.enabled": true,
   "gitlens.remotes": [
        {
            "domain": "github.int.[redacted]",
            "type": "GitHub"
        }
    ],
```
The integration works well on gitlens 14.5.2.

After updating to 14.6.0, gitlens tells me that I'm disconnected from the remote and need to connect. When trying to connect, a login to github.com is opened instead of the enterprise url. In the end, the remote stays disconnected even if I log in into github.com.

For now I've downgraded to 14.5.2 to make the integration work again.

### GitLens Version

14.5.2

### VS Code Version

Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

### Git Version

git version 2.43.0

**Comment by jkelroy** [comment]
@zuranthus this sounds related to #3088 and we did a refactor in the pre-release that may solve for this. Can you please see if this issue is still reproducible in the pre-release edition of GitLens?​

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/27739784/240437025-f9f6b0cf-cda3-4b53-973b-3689f1e4481a.png)

**Comment by zuranthus** [comment]
Not reproducible in the pre-release, the remote works fine 👍🏻 Thanks @jkelroy!
