### ISSUE TITLE
Commit search using files does not work as expected when file is in a multi-level directory

### ISSUE THREAD

**Issue by jkelroy** [gitkraken/vscode-gitlens#3086]
### Description

When a file is in a multi-level directory, the commit search on the commit graph will not always return the expected commits when searching by file.

1. Add a file to a multi-level directory i.e. ~\example\directory\folder\file.tst and commit
2. Open the commit graph and attempt to search for this file using `file:file.tst`

![Screenshot 2024-01-04 at 12 12 25 PM](https://github.com/gitkraken/vscode-gitlens/assets/27739784/a64c2818-f8d3-432f-8056-7510081dcd0f)
![Screenshot 2024-01-04 at 12 12 15 PM](https://github.com/gitkraken/vscode-gitlens/assets/27739784/2cba1abc-98cd-4557-b385-ea05f443eb05)

If this file exists in a single-level directory, the commit is returned. Also, if you use `File:file.tst` instead, the commit is returned as expected.

![Screenshot 2024-01-04 at 12 12 43 PM](https://github.com/gitkraken/vscode-gitlens/assets/27739784/61fb2735-4eca-4cd1-9726-1eab39b19ab6)

### GitLens Version

14.6.1

### VS Code Version

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z (3 wks ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.3.0

### Git Version

git version 2.41.0

**Comment by eamodio** [comment]
In 14.6.1, to fuzzily search by file name (in any subfolder) you need to use a glob pattern e.g. `**/file.txt` or `*file*` for partial matches.

In the current pre-release of GitLens I've added some fuzziness by default if the pattern in `file:<pattern>`  looks like a simple work or filename (without a path). For example if you enter `file:file.txt`, we effectively convert it to `file:**/file.txt`, or if you enter `file:readme` we convert it to `file:*readme*`.

Also the using `File:<pattern>` is no longer considered a pattern, we were incorrectly allowing any casing on the filter keywords -- they have to be all lowercase. That will be fixed in tomorrow's pre-release.

**Comment by axosoft-ramint** [comment]
Verified in the current pre-release.
