### ISSUE TITLE
GitLens stopped working from v12.0.0

### ISSUE THREAD

**Issue by Vezil** [gitkraken/vscode-gitlens#3096]
### Description

[GitLens stopped working in v12.0.0 and later](https://github.com/gitkraken/vscode-gitlens/issues/1979)

I have exactly same issue as above.

Since v12 it doesn't work till newest...
When I downgrade to v11.x.x the extension works. 

### GitLens Version

12.0.0+

### VS Code Version

1.85.1

### Git Version

git version 2.43.0.windows.1

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it? That referenced issue has a lot of different issues wrapped up. Also please make sure you are running the latest released version or pre-release.

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by Vezil** [comment]
@eamodio Issue resolved! 
Our project is remapping to another disc and when I run project directly from base disc everything works perfectly! Debug mode was very helpful because it has shown references to two discs and I concluded that something is wrong between references. Thank you!
