### ISSUE TITLE
Git lens not working on Ubuntu WSL

### ISSUE THREAD

**Issue by vitorklock** [gitkraken/vscode-gitlens#3097]
### Description

While using WSL (5.15.133.1-microsoft-standard-WSL2) opening VSCode via command on any git repository and Git Lens will not start. It worked fine on Ubuntu 22.04 LTS, but doesn't work on both my machines while running WSL.

The "**No repository detected**" warning still shows.

### GitLens Version

14.6.1

### VS Code Version

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.34.1

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it? How are you opening the WSL repository? Via the WSL extension?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!
