### ISSUE TITLE
Allow multi-select and delete for stashes

### ISSUE THREAD

**Issue by jcready** [gitkraken/vscode-gitlens#3102]
I have hundreds of stashes (don't @ me) which I'd like to selectively delete/drop. It would be super helpful if I could do something like "Select All" (click on first then shift click on last, or some other method), then be able to deselect ones I didn't want to delete/drop (control click, or some other method), and then finally be able to right-click and "Drop Stashes...".

**Comment by eamodio** [comment]
While its very experimental, if you are running the pre-release version of GitLens, you can set `"gitlens.views.experimental.multiSelect.enabled": true,` in your settings (and after a restart) you can multi-select in most GitLens views.

For most commands it currently just executes them in a loop, except for cherry-pick

**Comment by eamodio** [comment]
I've improved things so that you can now multiselect directly from the drop stash quickpick menus, and it provides a better experience when `"gitlens.views.experimental.multiSelect.enabled": true` is set.

Can you please verify this fix in tomorrow's (`v2024.01.16xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by axosoft-ramint** [comment]
Verified on the current pre-release.
