### ISSUE TITLE
Improve opening file revision on a rename

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#3109]
For consistency and to avoid confusion, could it make sense to still prompt for another file if the command is called with a file that is neither staged nor committed? It's a common use case for me to want to compare a renamed file with the one in history, and it will be kinda annoying to have to remember to first stage it temporarily just to do so (especially if I already have a busy staging area)

_Originally posted by @mogelbrod in https://github.com/gitkraken/vscode-gitlens/issues/3050#issuecomment-1854262983_

**Comment by eamodio** [comment]
Closed by 7636a6101bde91f19b48c66319deadade2ef35b3

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.01.25xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by mogelbrod** [comment]
> Can you please verify this fix in tomorrow's (`v2024.01.25xx`) pre-release edition of GitLens? Thank you so much!

Thanks work looking into this! I tried the pre-release now, and it seems like the fallback selected in the new dialog isn't propagated to the next step:

https://github.com/gitkraken/vscode-gitlens/assets/150084/20636c4e-73ca-4672-b231-9759fb96d342

Reproduction:
1. Rename a committed file (for example from `*.js` to `*.tsx`)
2. Open the file in vscode
3. Trigger the file revision gitlens command
4. Get prompted for another file (works as expected 👍  should perhaps only include deleted files rather than all modified files?)
5. Select the original file from the list
6. Select the revision to compare with

At this point I'd expect the old file at the selected revision to be opened, but instead another quick pick shows up, prompting me to enter the file name at the revision. If enter the old file name and continues it works as expected.

**Comment by eamodio** [comment]
@mogelbrod great catch! This should be resolved in tomorrow's pre-release. Thanks!
