### ISSUE TITLE
The checkmarks in cherry pick are not displayed

### ISSUE THREAD

**Issue by raspberry59** [gitkraken/vscode-gitlens#3179]
### Description

1. Open VS code on Mac OS
2. Open comand palette: cmd + shift + p
3. Choose: "GitLens: Git Cherry Pick..."
4. Choose any brach
5. Select one or more commits
6. Problem: the check marks of the selected commits are not displayed

### GitLens Version

14.9.0

### VS Code Version

Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:51.279Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

### Git Version

git version 2.35.1

### Logs, Screenshots, Screen Captures, etc

![RPXEkntWu](https://github.com/gitkraken/vscode-gitlens/assets/4845443/bb7dbad7-3d8d-48d1-9dab-e2bdf6f99269)

**Comment by eamodio** [comment]
Thanks for the report and sorry for the issues. This seems to have cropped up in some recent version of VS Code. I've been looking at this on and off for the last week or so (since we saw the same internally) but haven't been able to pinpoint where the problem is. I can repro using a stripped down experience within GitLens, but I can't repro it using a small sample and haven't yet identified the important difference.
