### ISSUE TITLE
Gitlens

### ISSUE THREAD

**Issue by Himanshu12866** [gitkraken/vscode-gitlens#3334]
### Description

In my VS Code gitlens is not working . I tried a lot but got the same result.

### GitLens Version

v15.0.4

### VS Code Version

1.89

### Git Version

 2.45.1

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by Himanshu12866** [comment]
I will try. Thank you 😊
