### ISSUE TITLE
Not recognizing git repository in opened folder in VS Code

### ISSUE THREAD

**Issue by jb-jonBoone** [gitkraken/vscode-gitlens#3416]
### Description

1. In this environment:
MacBook Pro w/Apple M3 Pro, 18 GB RAM

2. I opened a Node.js project under git source control.
3. 

### GitLens Version

15.2.0

### VS Code Version

Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

### Git Version

git version 2.45.2

### Logs, Screenshots, Screen Captures, etc

The extension is unable to recognize that I already have opened a folder containing a git repository, so the extension suggests that I open an issue.

![Screenshot 2024-07-23 at 15 53 32](https://github.com/user-attachments/assets/d4477b47-bcfe-4cb7-930a-6aab3de0acb0)

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it? How are you opening the repository -- locally, shared drive, remote extension, etc?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!
