### ISSUE TITLE
Cannot click on commit info window due to it disappearing when trying to hover it

### ISSUE THREAD

**Issue by AsparagusEduardo** [gitkraken/vscode-gitlens#3429]
### Description

1.- Previously, I was able to keep by mouse over a line's commit info and a window would pop up and give me options such as opening the commit on GitHub.
2.- Now, when I try to hover this window, it disappears.

### GitLens Version

15.2.1

### VS Code Version

Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

![Code_0Xi6NI60Fw](https://github.com/user-attachments/assets/dd3ce3cf-d19d-4d4e-8de3-d0c9459f697b)

**Comment by eamodio** [comment]
Unfortunately, there isn't anything GitLens can do here -- the hover trigger and behavior are completely controlled by VS Code. And this is an area of almost regular frustration, because things get fixed and broken repeatedly -- with numerous issues reported.  Though I do know they have been recently working on the hover itself, so it might be worth filing an issue especially if it is reproducible (I cannot reproduce it).

**Comment by AsparagusEduardo** [comment]
Thank you for the in-depth explanation. I followed VSCode's bug report procedures and it seems that as of right now, the issue doesn't manifest on the latest Insiders version, so it will be probably be fixed for next version of VSCode.
Cheers!
