### ISSUE TITLE
gitLens tips： No repository detected To use GitLens, open a folder containing a git repository or clone from a URL from the Explorer.

### ISSUE THREAD

**Issue by DuskwoodDane** [gitkraken/vscode-gitlens#3607]
### Description

I opened a folder containing.git, but gitlens kept telling me that there was no repository. I tried to use other repositories, and they all had the same problem, but my code could be submitted normally

### GitLens Version

15.5.1

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!
