### ISSUE TITLE
Start Work operation in Home view

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3621]
[Figma Flow Diagram](https://www.figma.com/board/einSHVwbXU9NeHOnnY0NMT/GitLens%3A-Start-Work-Flow?node-id=0-1&t=stWxxPzS1QMFUONU-1)

Add a "Start work" button to the Home view that opens a quick pick to initiate different flows for starting work (creating a branch).

Users should be able to create a branch, create a branch on a worktree (pro), and do either of those from an issue on a connected service (e.g, create a branch from a Jira issue).

New branches associated with issues will follow whatever naming conventions the service (e.g, Jira) requires to associate them.
- if users have specific autolinks setup to make these associations, we may want to consider those when creating branches for issues.

## Roadmap

- ✅ collect GitHub issues
- ✅ if we don't have an issue integration, suggest user to connect it. (can we have many issue providers? I believe, yes).
<img src="https://github.com/user-attachments/assets/2308f7b4-c036-42fa-8a99-96f3040e12ea" width="160"> <img src="https://github.com/user-attachments/assets/f666bafe-ef9e-4663-97b6-befe19d4c724" width="500">

- ✅ build compatible branch name based on issue title and id
  <img src="https://github.com/user-attachments/assets/8a6a230f-ee76-44b8-aed5-008622b240d0" width="400">

- ✅ Remove "read more about start work" section from "connect integrations" step:
  <img src="https://github.com/user-attachments/assets/84e36953-3650-437d-b066-9f68ba1eb6ed" width="600">

- ✅ when user selects a GitHub issue, highlight the corresponding repository on the "select repo" step

- ❌ ~~feature gate:~~
  <img src="https://github.com/user-attachments/assets/ecc4b797-4e69-4c17-adb0-2baaaf90373d" width="400">

- ✅ let user create a branch without selecting an issue (just send them to "create-branch" flow)
  <img src="https://github.com/user-attachments/assets/52062d8e-a4f4-4854-a14a-0b1ebabe313d" width="400">

- ✅ Jira issues
- ❌ (not valid anymore because that step has been removed, correct?) Once you select an issue, in the next step, the description line at the top sometimes doesn't look great because it renders much of the HTML stuff as plain text. However, the HTML is rendered very well on hover, which we would like to preserve. Eric suggested, to keep both, that we put a generic line like "Created by <author> x days ago" at the top of the description, then pad with a blank line, then can put the rest of the description. That should give us a better-looking and consistent description line in that step but also keep the HTML for the hover tooltip.
- ✅ filter Jira on **free** account
- ✅ Remove "create-branch" icon
- ✅ Make "Start Work" button open the "Start Work" quickpick
- ✅ fix wording
- 💡 filter issues to the current repo
- ✅ If I don't have integrations connected, when using the command, it immediately shows the "connect integration" step. This step should only show after I choose one of the "from an issue" options in the initial step.
- 💡 For Jira, I'm only seeing issues that I created/authored. It should show, and prioritize, issues I am assignee on, [like this one for example](https://gitkraken.atlassian.net/browse/GLVSC-427). Instead I am seeing issues I reported even if they have no assignee.
- ⏺️ switch to issue list before waiting for the result
- ⏺️ When clicking the "globe" icon on an issue to open that issue in the browser, we should not hide the quickpick. I'm seeing the same issue with Launchpad items as well, so perhaps there is a regression here or some issue with the debug window? (in the pre-release, if I click the globe to open a Launchpad PR in the browser, the quickpick stays open).
- ⏺️ testing

## Follow-ups

- ⏺️ The issue description/body is not showing in the hover tooltip of each issue. We used to have this at the "confirm" step where you could choose an action on that issue, but since that step is gone now, there is no way to read the issue description without opening the issue. We should have the current description, and then a blank line, and then the issue body, so that the current description lines show as they are now in the quickpick but if you hover over one of them, you can see the full issue body in the tooltip.

- ⏺️ Caching (Provider)
- ⏺️ what if provider requires to select a project first? add a corresponding screen that lists available projects.
<img src="https://github.com/user-attachments/assets/f87e9b2a-177f-4e43-aac1-6053f9b65fc2" width="200"> <img src="https://github.com/user-attachments/assets/0483883f-40b7-423c-83d2-2317ed10d0a1" width="400">  
 
- ⏺️ support other providers:
  - GitLab
  - Azure
  - Bitbucket?
  - ???

## Possible follow-ups

- on GIJ we let user to configure templates for branch naming, that support such fields as `issuekey`, `summary`, `username`, `displayname`, `projectkey`, `sourcebranch`
- we might want to let user configure default repository and default main branch for a specific project in issue management system.

**Comment by sergeibbb** [comment]
Hi @axosoft-ramint! I have a question for you.

How `PlusFeatures.Launchpad` is used? Do we need to create a `PlusFeatures.StartWork`?

https://github.com/gitkraken/vscode-gitlens/blob/cc12a35fbbf1ecea7f9d39d6cc317d983c4a8602/src/plus/startWork/startWork.ts#L134

**Comment by axosoft-ramint** [comment]
@sergeibbb good question. I believe this is used to gate Launchpad as a Pro feature (i.e. to require that the user have a Pro subscription to access it). The line you linked calls a step in the quickpick that ensures that the user has the right license before continuing with the Launchpad steps (if not, a message is presented to upgrade).

Might want to check with @eamodio and @justinrobots if we consider "Start Work" a pro feature. If so, yes we will want to add `PlusFeatures.StartWork` and add a similar step to it.

**Comment by sergeibbb** [comment]
Hi @axosoft-ramint 

What is the easiest way get a `Repository` by knowing its `IssueRepository`?
<img src="https://github.com/user-attachments/assets/e2690589-d315-4553-a78d-e73eeddc803b" width="350"> -> <img src="https://github.com/user-attachments/assets/11173363-1588-4df1-96ed-ec3ebffc4c11" width="500">

**Comment by axosoft-ramint** [comment]
@sergeibbb You will need 2 things:

1. Issues from provider query need to include repository url
2. Need to implement utility functions to get repo for issue, very similar to the ones for PRs

I have hacked together both of these here, for your convenience: https://github.com/gitkraken/vscode-gitlens/commit/dbfdf7eabf5652423bf3ad07c5c1163c21aee0aa

The functions should be moved to the right files and the typing is very similar to the ones for pull requests, so some merging of types may be possible.

Please have a look and feel free to adapt it in your own work.

**Comment by sergeibbb** [comment]
@axosoft-ramint 
Perfect! Thank you so much!

**Comment by sergeibbb** [comment]
Hi @justinrobots and @eamodio 

I need your feedback on what is done.

Here is how it looks on Home view. I haven't did much on it because I think that the new Home is in progress and coming soon. So, when it's done we'll easily link a button there to the "Start work" action:
<img src="https://github.com/user-attachments/assets/98d440db-a403-4478-a06c-79c66ca3793b" width="600">


Here is how it looks in the command palette:
<img src="https://github.com/user-attachments/assets/9a023c37-90b1-4709-8915-202d57086edd" width="800">


Here is how feature gate looks like:
<img src="https://github.com/user-attachments/assets/ecc4b797-4e69-4c17-adb0-2baaaf90373d" width="800">

This video demonstrates how the feature works:
https://github.com/user-attachments/assets/352b1b32-9fe8-4ac3-a90e-209550044816

On the video you can see how:
1. after picking an issue its repository is highlighted on the next screen, but we let user to change it if they want to start work on a satellite repository
2. crazy cyrillic issue title with Spanish letters and accents is nicely converted to a branch name

#### Next steps

What is done seems to be sufficient to be considered as minimal feature. So if we wanted to publish it as it we could do it. Therefore, I'm forming it to a PR and sending to the code review.

While the code is being reviewing, you're welcome to leave your feedback on what is done: any notes, suggestions, fixing of texts, etc.

At the same time I can continue on this issue in following directions:

- support Jira issues
- let user create a branch without selecting an issue (just send them to "create-branch" flow).
    <img src="https://github.com/user-attachments/assets/b822dc01-8f3f-433d-b811-dcdb701256a9" width="200">
  However, I doubt that we need it here.
- support GitLab, Azure, Bitbucket, etc.
- let user to configure default repository and main branch per project
- let user to configure branch name template

I think each item from above is detachable and can go as a separate ticket. So, please share your preference about:
1. what cannot be detached and must appear in the first published version
2. what is detachable but should go first
3. and what can be postponed or declined

**Comment by sergeibbb** [comment]
@justinrobots 

I have a question about this step:
![Image](https://github.com/user-attachments/assets/233a1dbd-daa7-4793-8547-15eb8e3d8429)


We have the following step on the creation a branch:
![Image](https://github.com/user-attachments/assets/e5670f28-e619-43bb-bf4a-0a7792e4229d)

Notice that there a 3d option in addition to just "create" and "create in worktree". It's "create and switch".

Also, there are few other steps related to opening in a Worktree:
![Image](https://github.com/user-attachments/assets/9b2582dd-de7e-46ad-8c17-802fd41934d4)

![Image](https://github.com/user-attachments/assets/abb6e2c6-4484-4006-a7c6-f3da5786c858)

---

❓ So we simplify the first screen and let user think about worktrees later? And at the beginning show this only:
![Image](https://github.com/user-attachments/assets/52062d8e-a4f4-4854-a14a-0b1ebabe313d)

**Comment by axosoft-ramint** [comment]
Verified in pre-release.
