### ISSUE TITLE
No search & compare anymore in v16.0.0

### ISSUE THREAD

**Issue by MCMattiaOetiker** [gitkraken/vscode-gitlens#3759]
### Description

After upgrading to v16.0.0 the search & compare tab is not available anymore

### GitLens Version

16.0.0

### VS Code Version

Version: 1.95.2 (system setup)
Release: 24313
Commit: 7656a0bea17ba6cf301721572e10c9035bb378e6
Date: 2024-11-09T10:44:38.190Z
Electron: 32.2.1
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

### Git Version

git version 2.45.1.windows.1

### Logs, Screenshots, Screen Captures, etc

In v15.6.3
![Image](https://github.com/user-attachments/assets/9dcaa6d8-adef-4a72-810e-52396144debc)

In v16.0.0 
![Image](https://github.com/user-attachments/assets/b1a64db8-0a75-4162-a248-a4190393c100)

**Comment by phil3741** [comment]
Can confirm. This is an absolutely essential feature for me

**Comment by gkhaavik** [comment]
I am getting "There is no data provider registered that can provide view data"

**Comment by phil3741** [comment]
it was moved to the Version Control Tab apparently.

![Image](https://github.com/user-attachments/assets/ea2eadc7-f020-4ba1-be5c-9f21dc8bbf4e)

**Comment by phil3741** [comment]
Apparently it was moved to the Version Control Tab


![Image](https://github.com/user-attachments/assets/1c3b2aea-b0fe-4072-b1ea-c2adcd8aa170)

**Comment by justinrobots** [comment]
Hey @MCMattiaOetiker we just pushed a fix for this specific issue to put `Search & Compare` back into GitLens Inspect. It was moved when we consolidated GitLens Source Control views. [This discussion](https://github.com/gitkraken/vscode-gitlens/discussions/3762) talks more about those consolidated views.

If you update GitLens this should be fixed. Otherwise, you can manually restore this by selecting "Detach Search & Compare View" from the `...` menu in the `GitLens` view header.
