### ISSUE TITLE
open any file from another branch

### ISSUE THREAD

**Issue by emmanueltouzery** [gitkraken/vscode-gitlens#708]
Recently https://github.com/eamodio/vscode-gitlens/issues/646 was implemented, but it doesn't completely work for me. The reason being that sometimes a file is renamed, and then the command (understandably) fails. In emacs/magit this is handled like that: you run the command, then by default the same filename as your current file is displayed and you just press enter if you want the same filename, but you can edit the filename if needed.

Maybe that gitlens feature, `gitlens.openFileRevisionFromBranch`, could be improved so that if it doesn't find the file in another branch, it doesn't fail but rather gives the user the opportunity to manually specify a filename.

In my case I renamed a `.ts` file to `.tsx`, but there could be many examples of renaming files.

**Comment by danielpickett** [comment]
I would LOVE this feature. Any movement on this?

**Comment by eamodio** [comment]
I can see this being a useful feature, but we (the GitLens team) aren't going to look at it anytime soon, so if the community wanted to open a PR for it we'd definitely be open to accepting it.

**Comment by mogelbrod** [comment]
I've got a PR up that implements this in https://github.com/gitkraken/vscode-gitlens/pull/2825

**Comment by eamodio** [comment]
Thanks to @mogelbrod's PR this has landed! Thank you!

Can you please verify this fix in tomorrow's (`v2023.12.06xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by mogelbrod** [comment]
@eamodio that's great! I tried the pre-release just now and encountered a potential issue:
- Open a project in vscode
- Rename a checked (committed) in file from `x.js` to `x.ts` or similar
- Open the file in vscode
- Trigger the "Open file at revision..." command

Expected behaviour: be presented with a revision picker
Actual behaviour: "Unable to show commit history"
<img width="627" alt="Screenshot 2023-12-07 at 11 28 53" src="https://github.com/gitkraken/vscode-gitlens/assets/150084/18acdbf0-97bd-4377-b21b-e7b542371e60">

Nothing logged to the GitLens output

**Comment by eamodio** [comment]
@mogelbrod that seems to be an existing bug, which I moved to #3050 (which will be fixed in tomorrow's pre-release)
